"""
╔══════════════════════════════════════════════════════════════════╗
║          NDA4 AI AGENT SOLANA TRADING BOT v2.0                  ║
║     Auto Trade | Auto Learn | Auto Improve | Paper Trading       ║
╚══════════════════════════════════════════════════════════════════╝

Gabungan dari:
- NDA4 AI Agent Trading Bot (scan + AI entry + Telegram)
- Memecoin Scanner Skill (paper trading + self-improving + journal)

Features:
- Real-time on-chain scanning (DexScreener + GMGN + Birdeye + pump.fun)
- AI Agent via OpenRouter: putuskan entry type, TP, SL, confidence score
- Entry Scoring System (0-100) mirip Memecoin Skill — butuh 70+ untuk BUY
- Paper trading mode (aman, bisa diaktifkan via PAPER_TRADE=true)
- Auto-improve filters setelah 3x loss berturut-turut
- Telegram: notif per trade + laporan tiap 1 jam
- Win Rate tracking + pattern library yang berkembang otomatis
- Trading Journal (.md) yang di-update setelah setiap trade
- Risk management rules yang ketat
"""

import asyncio
import aiohttp
import json
import logging
import os
import time
import copy
from datetime import datetime, timedelta
from typing import Optional
from dataclasses import dataclass, field
from collections import deque
from pathlib import Path

# ──────────────────────────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────────────────────────
# Load .env file if present (for local dev / github repo)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

TELEGRAM_BOT_TOKEN   = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID     = os.getenv("TELEGRAM_CHAT_ID", "1404877677")
OPENROUTER_API_KEY   = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL     = os.getenv("OPENROUTER_MODEL", "openrouter/owl-alpha")
OPENROUTER_BASE_URL  = "https://openrouter.ai/api/v1/chat/completions"
GMGN_API_KEY         = os.getenv("GMGN_API_KEY")

# Mode: set PAPER_TRADE=false untuk live (hati-hati!)
PAPER_TRADE          = os.getenv("PAPER_TRADE", "true").lower() != "false"

# Trading parameters
INITIAL_BALANCE_SOL       = float(os.getenv("INITIAL_BALANCE", "1.0"))
TRADE_SIZE_SOL            = float(os.getenv("TRADE_SIZE", "0.03"))
MAX_OPEN_TRADES           = int(os.getenv("MAX_OPEN_TRADES", "10"))
SCAN_INTERVAL_SEC         = int(os.getenv("SCAN_INTERVAL", "60"))
REPORT_INTERVAL_SEC       = 3600
TARGET_WIN_RATE           = 0.55
CONSECUTIVE_LOSS_TRIGGER  = 3
MIN_ENTRY_SCORE           = 55       # Minimum score 0-100 untuk BUY
MAX_DAILY_LOSS_PCT        = 0.20     # Stop trading jika portfolio turun 20% sehari
MAX_CONSECUTIVE_LOSSES    = 5        # Pause jika 5x loss berturut-turut
STOP_LOSS_PCT             = 0.30     # Default hard SL -30%
CHASE_LIMIT_MULTIPLIER    = 3.0      # Jangan chase token yang sudah 3x

# Paths untuk journal & strategi
REFERENCES_DIR   = Path("references")
JOURNAL_FILE     = REFERENCES_DIR / "trading_journal.md"
STRATEGY_FILE    = REFERENCES_DIR / "strategy_evolution.md"
WATCHLIST_FILE   = REFERENCES_DIR / "wallet_watchlist.md"
BLACKLIST_FILE   = REFERENCES_DIR / "token_blacklist.md"

# ──────────────────────────────────────────────────────────────────
# REFERENCE FILE MANAGER
# ──────────────────────────────────────────────────────────────────

def init_reference_files():
    """Buat folder & file referensi jika belum ada"""
    REFERENCES_DIR.mkdir(exist_ok=True)

    if not JOURNAL_FILE.exists():
        JOURNAL_FILE.write_text("# Trading Journal\n\n_Auto-generated by NDA4 Bot v2_\n\n")

    if not STRATEGY_FILE.exists():
        STRATEGY_FILE.write_text(
            "# Strategy Evolution\n\n_Auto-generated by NDA4 Bot v2_\n\n"
            "## Initial Strategy — Generation 1\n"
            "- Min liquidity: $15k\n- Min volume 24h: $10k\n- Min holders: 100\n"
            "- Buy/sell ratio: 1.5x\n- TP: +25% | SL: -8%\n\n"
        )

    if not WATCHLIST_FILE.exists():
        WATCHLIST_FILE.write_text("# Smart Money Wallet Watchlist\n\n_Add wallets to track here_\n\n")

    if not BLACKLIST_FILE.exists():
        BLACKLIST_FILE.write_text("# Token Blacklist\n\n_Tokens/patterns to avoid_\n\n")


def append_to_journal(text: str):
    try:
        with open(JOURNAL_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Journal write error: {e}")


def append_to_strategy(text: str):
    try:
        with open(STRATEGY_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Strategy write error: {e}")


# ──────────────────────────────────────────────────────────────────
# DATA STRUCTURES
# ──────────────────────────────────────────────────────────────────

@dataclass
class FilterConfig:
    """AI-tunable filter parameters — auto-improved saat sering loss"""
    min_liquidity_usd: float   = 1_000
    min_volume_24h_usd: float  = 500
    min_holder_count: int      = 5
    max_price_impact_pct: float = 15.0
    min_price_change_5m: float = -5.0
    max_price_change_5m: float = 100.0
    min_tx_count_5m: int       = 0
    min_buy_sell_ratio: float  = 0.0
    min_market_cap_usd: float  = 1_000
    max_market_cap_usd: float  = 50_000_000
    require_renounced: bool    = False
    require_burned_lp: bool    = False
    bundle_threshold: float    = 0.25
    min_age_minutes: int       = 5
    max_age_hours: int         = 24
    tp_multiplier: float       = 1.25
    sl_multiplier: float       = 0.90
    generation: int            = 1

    def to_prompt(self) -> str:
        return f"""
CURRENT FILTER CONFIG (Generation {self.generation}):
- Minimum Liquidity: ${self.min_liquidity_usd:,.0f}
- Minimum 24h Volume: ${self.min_volume_24h_usd:,.0f}
- Minimum Holders: {self.min_holder_count}
- Max Price Impact: {self.max_price_impact_pct}%
- Price Change 5m Range: {self.min_price_change_5m}% - {self.max_price_change_5m}%
- Min Tx 5m: {self.min_tx_count_5m}
- Min Buy/Sell Ratio: {self.min_buy_sell_ratio}x
- Market Cap Range: ${self.min_market_cap_usd:,.0f} - ${self.max_market_cap_usd:,.0f}
- Max Bundle %: {self.bundle_threshold*100:.0f}%
- Token Age: {self.min_age_minutes}m - {self.max_age_hours}h
- TP: +{(self.tp_multiplier-1)*100:.0f}% | SL: -{(1-self.sl_multiplier)*100:.0f}%
"""


@dataclass
class TokenData:
    """Raw data dari scanner"""
    address: str
    symbol: str
    name: str
    price_usd: float
    price_sol: float
    liquidity_usd: float
    volume_24h: float
    volume_5m: float
    price_change_5m: float
    price_change_1h: float
    price_change_24h: float
    market_cap: float
    holder_count: int
    tx_count_5m: int
    buy_count_5m: int
    sell_count_5m: int
    age_minutes: float
    dex: str
    pair_address: str
    buy_sell_ratio: float = 0.0
    # GMGN-specific fields
    rug_ratio: float = 0.0
    smart_degen_count: int = 0
    renowned_count: int = 0
    renounced_mint: bool = False
    renounced_freeze: bool = False
    is_wash_trading: bool = False
    hot_level: int = 0
    creator_token_status: str = ""
    is_honeypot: bool = False
    top_10_holder_rate: float = 0.0
    dev_token_burn_ratio: float = 0.0
    cto_flag: bool = False
    scanned_at: float = field(default_factory=time.time)

    def entry_score(self) -> int:
        """
        Hitung entry score 0-100 untuk token baru.
        Lebih longgar — fokus ke momentum dan buy pressure.
        GMGN data: rug_ratio, smart_degen, renounced, wash_trading, hot_level.
        """
        score = 0

        # Liquidity (0-15) — token baru biasanya kecil
        if self.liquidity_usd >= 20_000:
            score += 15
        elif self.liquidity_usd >= 10_000:
            score += 12
        elif self.liquidity_usd >= 5_000:
            score += 8
        elif self.liquidity_usd >= 1_000:
            score += 4

        # Holders (0-10) — token baru biasanya sedikit
        if self.holder_count >= 100:
            score += 10
        elif self.holder_count >= 50:
            score += 7
        elif self.holder_count >= 20:
            score += 5
        elif self.holder_count >= 5:
            score += 2

        # Momentum 5m (0-20) — yang penting ada gerak
        if 2 <= self.price_change_5m <= 30:
            score += 20
        elif 1 <= self.price_change_5m <= 50:
            score += 15
        elif 0.5 <= self.price_change_5m <= 1:
            score += 10
        elif -5 <= self.price_change_5m < 0.5:
            score += 5

        # Buy/sell ratio (0-10) — buy > sell = bagus
        ratio = self.buy_count_5m / self.sell_count_5m if self.sell_count_5m > 0 else (self.buy_count_5m if self.buy_count_5m > 0 else 0)
        if ratio >= 2.0:
            score += 10
        elif ratio >= 1.5:
            score += 7
        elif ratio >= 1.0:
            score += 5
        elif ratio > 0:
            score += 2

        # Volume 24h (0-10) — ada volume = ada minat
        if self.volume_24h >= 50_000:
            score += 10
        elif self.volume_24h >= 10_000:
            score += 7
        elif self.volume_24h >= 1_000:
            score += 4

        # Age (0-10) — terlalu baru = risky, terlalu lama = gak ada momentum
        if 5 <= self.age_minutes <= 120:
            score += 10
        elif 1 <= self.age_minutes <= 360:
            score += 7
        elif self.age_minutes > 360:
            score += 3

        # GMGN: Smart money (0-10) — smart degen & renowned holders
        if self.smart_degen_count >= 5:
            score += 7
        elif self.smart_degen_count >= 2:
            score += 5
        elif self.smart_degen_count >= 1:
            score += 3
        if self.renowned_count >= 3:
            score += 3
        elif self.renowned_count >= 1:
            score += 2

        # GMGN: Safety (0-10) — renounced, no wash, low rug
        if self.renounced_mint and self.renounced_freeze:
            score += 4
        elif self.renounced_mint or self.renounced_freeze:
            score += 2
        if not self.is_wash_trading:
            score += 3
        if self.rug_ratio <= 0.1:
            score += 3
        elif self.rug_ratio <= 0.3:
            score += 1

        # GMGN: Hot level (0-5)
        if self.hot_level >= 3:
            score += 5
        elif self.hot_level >= 2:
            score += 3
        elif self.hot_level >= 1:
            score += 1

        # Penalty: creator masih hold (sell pressure risk)
        if self.creator_token_status == "creator_hold":
            score -= 5
        elif self.creator_token_status == "creator_close":
            score += 2

        # Penalty: top 10 holder rate tinggi = concentrated
        if self.top_10_holder_rate >= 0.5:
            score -= 5
        elif self.top_10_holder_rate >= 0.3:
            score -= 2

        # Penalty: honeypot
        if self.is_honeypot:
            score -= 20

        return max(0, min(score, 100))


@dataclass
class Trade:
    """Satu posisi trading"""
    id: str
    token_address: str
    token_symbol: str
    entry_type: str
    entry_price: float
    entry_price_sol: float
    tp_price: float
    sl_price: float
    size_sol: float
    status: str
    opened_at: float
    entry_score: int = 0
    closed_at: Optional[float] = None
    exit_price: Optional[float] = None
    pnl_sol: Optional[float] = None
    pnl_pct: Optional[float] = None
    ai_reasoning: str = ""
    current_price: float = 0.0
    last_updated: float = field(default_factory=time.time)
    is_paper: bool = True
    gmgn_data: Optional[dict] = None

    @property
    def is_active(self):
        return self.status in ("open", "pending_limit")

    @property
    def pnl_display(self):
        if self.pnl_sol is None:
            if self.status == "open" and self.current_price:
                pnl = (self.current_price - self.entry_price) / self.entry_price * self.size_sol
                return f"{pnl:+.4f} SOL ({(self.current_price/self.entry_price-1)*100:+.1f}%)"
            return "—"
        return f"{self.pnl_sol:+.4f} SOL ({self.pnl_pct:+.1f}%)"

    @property
    def duration_str(self) -> str:
        end = self.closed_at or time.time()
        mins = int((end - self.opened_at) / 60)
        if mins < 60:
            return f"{mins}m"
        return f"{mins//60}h {mins%60}m"


@dataclass
class BotState:
    """State lengkap bot"""
    balance_sol: float             = INITIAL_BALANCE_SOL
    initial_balance_sol: float     = INITIAL_BALANCE_SOL
    trades: list                   = field(default_factory=list)
    filters: FilterConfig          = field(default_factory=FilterConfig)
    consecutive_losses: int        = 0
    total_trades: int              = 0
    winning_trades: int            = 0
    losing_trades: int             = 0
    total_pnl_sol: float           = 0.0
    improve_count: int             = 0
    started_at: float              = field(default_factory=time.time)
    last_report_at: float          = field(default_factory=time.time)
    scanned_tokens_today: int      = 0
    skipped_tokens_today: int      = 0
    daily_loss_triggered: bool     = False
    paused_due_to_losses: bool     = False
    recent_losses: deque           = field(default_factory=lambda: deque(maxlen=10))
    trade_counter: int             = 0

    @property
    def win_rate(self) -> float:
        finished = self.winning_trades + self.losing_trades
        return self.winning_trades / finished if finished > 0 else 0.0

    @property
    def open_trades(self):
        return [t for t in self.trades if t.is_active]

    @property
    def finished_trades(self):
        return [t for t in self.trades if not t.is_active]

    @property
    def portfolio_change_pct(self) -> float:
        if self.initial_balance_sol == 0:
            return 0.0
        return (self.balance_sol - self.initial_balance_sol) / self.initial_balance_sol

    def can_open_trade(self) -> bool:
        if self.daily_loss_triggered:
            return False
        if self.paused_due_to_losses:
            return False
        if len(self.open_trades) >= MAX_OPEN_TRADES:
            return False
        if self.balance_sol < TRADE_SIZE_SOL:
            return False
        return True

    def check_daily_loss_limit(self) -> bool:
        """Return True jika daily loss limit terpicu"""
        if self.portfolio_change_pct <= -MAX_DAILY_LOSS_PCT:
            self.daily_loss_triggered = True
            return True
        return False

    def new_trade_id(self) -> str:
        self.trade_counter += 1
        return f"T{self.trade_counter:04d}"


# ──────────────────────────────────────────────────────────────────
# SCANNER — GMGN (primary) + DexScreener (fallback)
# ──────────────────────────────────────────────────────────────────

class SolanaScanner:
    DEXSCREENER_BASE = "https://api.dexscreener.com/latest/dex"
    BOOST_URL        = "https://api.dexscreener.com/token-boosts/latest/v1"

    async def _gmgn_cli(self, args: list[str]) -> Optional[dict]:
        """Call gmgn-cli via subprocess (bypasses Cloudflare via Node.js TLS)"""
        cmd = ["gmgn-cli"] + args
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=20)
            if proc.returncode != 0:
                err = stderr.decode().strip()
                logging.debug(f"gmgn-cli error: {err[:200]}")
                return None
            return json.loads(stdout.decode())
        except Exception as e:
            logging.debug(f"gmgn-cli call error: {e}")
            return None

    async def get_trending_tokens(self, session: aiohttp.ClientSession) -> list[TokenData]:
        """GMGN trending tokens (hot, volume, smart money)"""
        tokens = []
        data = await self._gmgn_cli(["market", "trending", "--chain", "sol", "--interval", "5m"])
        if not data:
            return await self._fallback_trending(session)
        if data.get("code") != 0:
            logging.warning(f"GMGN trending error: {data.get('msg', 'unknown')}")
            return await self._fallback_trending(session)
        rank = (data.get("data") or {}).get("rank") or []
        for item in rank[:25]:
            token = self._parse_gmgn_token(item)
            if token:
                tokens.append(token)
        return tokens

    async def get_new_tokens(self, session: aiohttp.ClientSession) -> list[TokenData]:
        """GMGN trenches — new pump.fun tokens"""
        tokens = []
        data = await self._gmgn_cli(["market", "trenches", "--chain", "sol", "--type", "new_creation"])
        if not data:
            return await self._fallback_new(session)
        # Trenches response: {"new_creation": [...], "completed": [...], ...}
        items = data.get("new_creation") or data.get("data", {}).get("list") or []
        if not items:
            # Try other keys
            for key in ("new_creation", "near_completion", "completed"):
                items = data.get(key) or []
                if items:
                    break
        for item in items[:20]:
            token = self._parse_gmgn_token(item)
            if token:
                tokens.append(token)
        return tokens
        return tokens

    async def get_token_detail(self, session: aiohttp.ClientSession, address: str) -> Optional[TokenData]:
        """GMGN token detail via gmgn-cli"""
        data = await self._gmgn_cli(["market", "kline", "--chain", "sol", "--address", address, "--resolution", "5m", "--limit", "1"])
        if not data:
            return None
        if data.get("code") != 0:
            return None
        # kline returns different format, try to get from trending instead
        return None

    def _parse_gmgn_token(self, item: dict) -> Optional[TokenData]:
        """Parse GMGN token data ke TokenData"""
        try:
            address = item.get("address", "")
            symbol = item.get("symbol", "???")
            name = item.get("name", "Unknown")
            price_usd = float(item.get("price", 0) or 0)
            # Trenches tokens may not have price yet — skip if zero
            if price_usd <= 0:
                # Try to get price from liquidity / supply
                liq_val = float(item.get("initial_liquidity", 0) or item.get("liquidity", 0) or 0)
                if liq_val > 0:
                    price_usd = liq_val / 1e9  # rough estimate
                else:
                    return None

            # Price changes
            pc = item.get("price_change_percent") or item.get("priceChange") or {}
            if isinstance(pc, (int, float)):
                ch5m = float(pc)
                ch1h = 0.0
                ch24h = 0.0
            else:
                ch5m = float(pc.get("m5", 0) or pc.get("price_change_percent5m", 0) or 0)
                ch1h = float(pc.get("h1", 0) or pc.get("price_change_percent1h", 0) or 0)
                ch24h = float(pc.get("h24", 0) or pc.get("price_change_percent24h", 0) or 0)

            # Volume
            vol = item.get("volume") or {}
            if isinstance(vol, (int, float)):
                vol_24h = float(vol)
                vol_5m = 0.0
            else:
                vol_24h = float(vol.get("h24", 0) or vol.get("volume24h", 0) or 0)
                vol_5m = float(vol.get("m5", 0) or vol.get("volume5m", 0) or 0)

            # Transactions - handle both trending and trenches format
            swaps = item.get("swaps") or item.get("txns") or {}
            if isinstance(swaps, (int, float)):
                total_swaps = int(swaps)
                buys_5m = total_swaps // 2
                sells_5m = total_swaps - buys_5m
            else:
                buys_5m = int(swaps.get("buys", 0) or swaps.get("buy", 0) or 0)
                sells_5m = int(swaps.get("sells", 0) or swaps.get("sell", 0) or 0)
                total_swaps = buys_5m + sells_5m
            # Trenches format: buys_24h, sells_24h
            if buys_5m == 0 and sells_5m == 0:
                buys_5m = int(item.get("buys_24h", 0) or 0)
                sells_5m = int(item.get("sells_24h", 0) or 0)
                total_swaps = buys_5m + sells_5m

            # Age - handle trenches format
            created_at = item.get("open_timestamp", 0) or item.get("creation_timestamp", 0) or item.get("created_timestamp", 0) or 0
            if created_at > 1e12:
                created_at = created_at / 1000
            age_minutes = max(0, (time.time() - created_at) / 60) if created_at > 0 else 0

            # Buy/sell ratio
            ratio = buys_5m / sells_5m if sells_5m > 0 else (999.0 if buys_5m > 0 else 0.0)

            # GMGN-specific
            rug_ratio = float(item.get("rug_ratio", 0) or 0)
            smart_degen = int(item.get("smart_degen_count", 0) or item.get("bot_degen_count", 0) or 0)
            renowned = int(item.get("renowned_count", 0) or 0)
            renounced_mint = bool(item.get("renounced_mint", 0))
            renounced_freeze = bool(item.get("renounced_freeze_account", 0))
            is_wash = bool(item.get("is_wash_trading", False))
            hot_level = int(item.get("hot_level", 0) or 0)
            creator_status = item.get("creator_token_status", "") or ""
            is_honeypot = bool(item.get("is_honeypot", False))
            top10_rate = float(item.get("top_10_holder_rate", 0) or item.get("creator_balance_rate", 0) or 0)
            dev_burn_ratio = float(item.get("dev_token_burn_ratio", 0) or 0)
            cto = bool(item.get("cto_flag", 0))

            return TokenData(
                address=address,
                symbol=symbol,
                name=name,
                price_usd=price_usd,
                price_sol=float(item.get("price_native", 0) or 0),
                liquidity_usd=float(item.get("liquidity", 0) or 0),
                volume_24h=vol_24h,
                volume_5m=vol_5m,
                price_change_5m=ch5m,
                price_change_1h=ch1h,
                price_change_24h=ch24h,
                market_cap=float(item.get("market_cap", 0) or item.get("marketCap", 0) or 0),
                holder_count=int(item.get("holder_count", 0) or 0),
                tx_count_5m=total_swaps,
                buy_count_5m=buys_5m,
                sell_count_5m=sells_5m,
                buy_sell_ratio=ratio,
                age_minutes=age_minutes,
                dex=item.get("dex", "") or item.get("exchange", "") or "unknown",
                pair_address=item.get("pair_address", "") or "",
                rug_ratio=rug_ratio,
                smart_degen_count=smart_degen,
                renowned_count=renowned,
                renounced_mint=renounced_mint,
                renounced_freeze=renounced_freeze,
                is_wash_trading=is_wash,
                hot_level=hot_level,
                creator_token_status=creator_status,
                is_honeypot=is_honeypot,
                top_10_holder_rate=top10_rate,
                dev_token_burn_ratio=dev_burn_ratio,
                cto_flag=cto,
            )
        except Exception as e:
            logging.debug(f"GMGN parse error: {e}")
            return None

    async def _fallback_trending(self, session: aiohttp.ClientSession) -> list[TokenData]:
        """Fallback: DexScreener token-boosts"""
        tokens = []
        try:
            async with session.get(self.BOOST_URL, timeout=aiohttp.ClientTimeout(total=10)) as r:
                if r.status != 200:
                    return tokens
                boosts = await r.json()
            if not isinstance(boosts, list):
                return tokens
            for boost in boosts[:15]:
                addr = boost.get("tokenAddress", "")
                if not addr:
                    continue
                try:
                    async with session.get(
                        f"{self.DEXSCREENER_BASE}/tokens/{addr}",
                        timeout=aiohttp.ClientTimeout(total=8)
                    ) as r:
                        if r.status != 200:
                            continue
                        data = await r.json()
                        pairs = data.get("pairs") or []
                        if not pairs:
                            continue
                        best = max(pairs, key=lambda x: float(x.get("liquidity", {}).get("usd", 0) or 0))
                        token = self._parse_dex_pair(best)
                        if token:
                            tokens.append(token)
                except Exception:
                    continue
                await asyncio.sleep(0.3)
        except Exception as e:
            logging.warning(f"Fallback trending error: {e}")
        return tokens

    async def _fallback_new(self, session: aiohttp.ClientSession) -> list[TokenData]:
        """Fallback: DexScreener search"""
        tokens = []
        try:
            url = f"{self.DEXSCREENER_BASE}/search?q=pump+fun+solana"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=12)) as r:
                if r.status != 200:
                    return tokens
                data = await r.json()
                pairs = data.get("pairs") or []
            sol_pairs = [p for p in pairs if p.get("chainId") == "solana"]
            for p in sol_pairs[:20]:
                token = self._parse_dex_pair(p)
                if token:
                    tokens.append(token)
        except Exception as e:
            logging.warning(f"Fallback new tokens error: {e}")
        return tokens

    def _parse_dex_pair(self, p: dict) -> Optional[TokenData]:
        """Parse DexScreener pair ke TokenData (fallback)"""
        try:
            base = p.get("baseToken", {})
            price_usd = float(p.get("priceUsd", 0) or 0)
            if price_usd <= 0:
                return None
            liq = p.get("liquidity", {})
            vol = p.get("volume", {})
            pc = p.get("priceChange", {})
            txns_5m = p.get("txns", {}).get("m5", {})
            info = p.get("info", {})
            created_at = p.get("pairCreatedAt", 0)
            age_minutes = (time.time() * 1000 - (created_at or time.time() * 1000)) / 60000
            holders = 0
            for ext in (info.get("extensions") or []):
                if isinstance(ext, dict) and ext.get("type") == "holders":
                    holders = int(ext.get("value", 0))
            buy5 = int(txns_5m.get("buys", 0) or 0)
            sell5 = int(txns_5m.get("sells", 0) or 0)
            ratio = buy5 / sell5 if sell5 > 0 else (999.0 if buy5 > 0 else 0.0)
            return TokenData(
                address=base.get("address", ""),
                symbol=base.get("symbol", "???"),
                name=base.get("name", "Unknown"),
                price_usd=price_usd,
                price_sol=float(p.get("priceNative", 0) or 0),
                liquidity_usd=float(liq.get("usd", 0) or 0),
                volume_24h=float(vol.get("h24", 0) or 0),
                volume_5m=float(vol.get("m5", 0) or 0),
                price_change_5m=float(pc.get("m5", 0) or 0),
                price_change_1h=float(pc.get("h1", 0) or 0),
                price_change_24h=float(pc.get("h24", 0) or 0),
                market_cap=float(p.get("marketCap", 0) or 0),
                holder_count=holders,
                tx_count_5m=buy5 + sell5,
                buy_count_5m=buy5,
                sell_count_5m=sell5,
                buy_sell_ratio=ratio,
                age_minutes=max(0, age_minutes),
                dex=p.get("dexId", "unknown"),
                pair_address=p.get("pairAddress", ""),
            )
        except Exception:
            return None


# ──────────────────────────────────────────────────────────────────
# FILTER ENGINE — Hard filters sebelum AI
# ──────────────────────────────────────────────────────────────────

class FilterEngine:
    def passes(self, token: TokenData, cfg: FilterConfig) -> tuple[bool, str]:
        if token.liquidity_usd < cfg.min_liquidity_usd:
            return False, f"Liquidity ${token.liquidity_usd:,.0f} < ${cfg.min_liquidity_usd:,.0f}"
        if token.volume_24h < cfg.min_volume_24h_usd:
            return False, f"Volume24h ${token.volume_24h:,.0f} < ${cfg.min_volume_24h_usd:,.0f}"
        if token.price_change_5m < cfg.min_price_change_5m:
            return False, f"Momentum 5m {token.price_change_5m:+.1f}% terlalu lemah"
        if token.price_change_5m > cfg.max_price_change_5m:
            return False, f"Pump 5m {token.price_change_5m:+.1f}% terlalu tinggi (risiko dump)"
        if token.tx_count_5m < cfg.min_tx_count_5m:
            return False, f"Tx 5m {token.tx_count_5m} < {cfg.min_tx_count_5m}"
        if 0 < token.market_cap < cfg.min_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu kecil"
        if token.market_cap > cfg.max_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu besar"
        if token.age_minutes < cfg.min_age_minutes:
            return False, f"Token terlalu baru ({token.age_minutes:.0f}m)"
        if token.age_minutes > cfg.max_age_hours * 60:
            return False, f"Token terlalu lama ({token.age_minutes/60:.1f}h)"
        if token.sell_count_5m > 0:
            ratio = token.buy_count_5m / token.sell_count_5m
            if ratio < cfg.min_buy_sell_ratio:
                return False, f"Buy/Sell ratio {ratio:.1f}x < {cfg.min_buy_sell_ratio}x"
        if token.holder_count > 0 and token.holder_count < cfg.min_holder_count:
            return False, f"Holders {token.holder_count} < {cfg.min_holder_count}"
        # GMGN: wash trading check
        if token.is_wash_trading:
            return False, "Wash trading detected"
        # GMGN: honeypot check
        if token.is_honeypot:
            return False, "Honeypot detected"
        # GMGN: rug ratio check
        if token.rug_ratio > 0.5:
            return False, f"Rug ratio {token.rug_ratio:.2f} too high"
        # GMGN: top 10 holder concentration
        if token.top_10_holder_rate > 0.7:
            return False, f"Top 10 holders {token.top_10_holder_rate:.0%} too concentrated"
        return True, ""


# ──────────────────────────────────────────────────────────────────
# AI AGENT — OpenRouter decides entry, TP, SL, improves filters
# ──────────────────────────────────────────────────────────────────

class AIAgent:
    def __init__(self):
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://github.com/aldiboncel49-lgtm/tes/",
            "X-Title": "NDA4 Solana Trading Bot v2",
        }

    async def _call_api(self, session: aiohttp.ClientSession, prompt: str, max_tokens: int = 500, retries: int = 2) -> Optional[str]:
        payload = {
            "model": OPENROUTER_MODEL,
            "max_tokens": max_tokens,
            "messages": [{"role": "user", "content": prompt}]
        }
        for attempt in range(retries + 1):
            try:
                async with session.post(
                    OPENROUTER_BASE_URL,
                    headers=self.headers,
                    json=payload,
                    timeout=aiohttp.ClientTimeout(total=45)
                ) as r:
                    if r.status == 429:
                        wait = 10 * (attempt + 1)
                        logging.warning(f"OpenRouter rate limit, waiting {wait}s...")
                        await asyncio.sleep(wait)
                        continue
                    if r.status != 200:
                        err = await r.text()
                        logging.error(f"OpenRouter error {r.status}: {err[:200]}")
                        return None
                    data = await r.json()
                    try:
                        content = data["choices"][0]["message"]["content"]
                        if content is None:
                            logging.error("OpenRouter response content is None")
                            return None
                        return content.strip()
                    except (KeyError, IndexError) as e:
                        logging.error(f"OpenRouter response parse error: {e} | data: {str(data)[:300]}")
                        return None
            except asyncio.TimeoutError:
                logging.warning(f"OpenRouter timeout (attempt {attempt+1}/{retries+1})")
                if attempt < retries:
                    await asyncio.sleep(10 * (attempt + 1))
                    continue
                return None
            except Exception as e:
                logging.error(f"OpenRouter call error: {e}")
                return None
        return None

    async def analyze_token(
        self, session: aiohttp.ClientSession, token: TokenData, state: BotState
    ) -> Optional[dict]:
        score = token.entry_score()
        prompt = f"""
Kamu adalah AI trading agent Solana on-chain yang konservatif dan disiplin.

{state.filters.to_prompt()}

TOKEN DATA (REAL-TIME):
- Symbol: {token.symbol} ({token.name})
- Address: {token.address}
- Price: ${token.price_usd:.8f} ({token.price_sol:.8f} SOL)
- Liquidity: ${token.liquidity_usd:,.0f}
- Volume 24h: ${token.volume_24h:,.0f}
- Volume 5m: ${token.volume_5m:,.0f}
- Price Change 5m/1h/24h: {token.price_change_5m:+.1f}% / {token.price_change_1h:+.1f}% / {token.price_change_24h:+.1f}%
- Market Cap: ${token.market_cap:,.0f}
- Holders: {token.holder_count}
- Tx 5m: {token.tx_count_5m} (Buy: {token.buy_count_5m} | Sell: {token.sell_count_5m})
- Age: {token.age_minutes:.0f} menit
- DEX: {token.dex}
- Entry Score (pre-calc): {score}/100

GMGN ON-CHAIN INTEL:
- Rug Ratio: {token.rug_ratio:.2f} (0=safe, 1=risky, reject if >0.5)
- Smart Degen Count: {token.smart_degen_count} (smart money wallets)
- Renowned Count: {token.renowned_count} (KOL wallets)
- Renounced Mint: {'✅' if token.renounced_mint else '❌'}
- Renounced Freeze: {'✅' if token.renounced_freeze else '❌'}
- Wash Trading: {'⚠️ YES' if token.is_wash_trading else '✅ No'}
- Hot Level: {token.hot_level}/5 (higher = more active)
- Creator Status: {token.creator_token_status or 'unknown'} (creator_close=good, creator_hold=risk)
- Top 10 Holder Rate: {token.top_10_holder_rate:.0%} (lower=better, reject if >70%)
- Dev Burn Ratio: {token.dev_token_burn_ratio:.0%}
- CTO Flag: {'✅' if token.cto_flag else '❌'} (community takeover)
- Honeypot: {'⚠️ YES' if token.is_honeypot else '✅ No'}

BOT STATE:
- Balance: {state.balance_sol:.3f} SOL
- Trade size: {TRADE_SIZE_SOL} SOL
- Open trades: {len(state.open_trades)}/{MAX_OPEN_TRADES}
- Current Win Rate: {state.win_rate*100:.1f}%
- Consecutive losses: {state.consecutive_losses}
- Total trades: {state.total_trades}
- Mode: {"PAPER TRADING" if PAPER_TRADE else "LIVE"}

RISK RULES:
- Ini PAPER TRADING — boleh lebih agresif, tapi tetap disiplin
- Jangan BUY jika rug_ratio > 0.5 atau is_honeypot = true (hard filter sudah handle ini)
- Jangan BUY jika sudah 5+ consecutive losses (paused)
- Minimum entry score: {MIN_ENTRY_SCORE}/100 (sudah di-filter sebelum sampai sini)
- TP minimal 20% di atas entry, SL maksimal -10% dari entry
- Token baru (< 1 jam) boleh masuk tapi confidence harus >= 30

INSTRUKSI:
1. Evaluasi semua data di atas — ini token yang sudah lolos filter ketat
2. Putuskan: BUY atau SKIP
3. Jika BUY: tentukan entry_type (market/limit), entry_price, tp_price, sl_price
   - limit: entry 1-2% di bawah harga sekarang
   - market: entry di harga sekarang
4. Berikan confidence score 0-100
   - confidence >= 30 untuk token baru (< 1 jam)
   - confidence >= 20 untuk token > 1 jam
   - Semakin bagus data (smart money, renounced, hot), semakin tinggi confidence
5. Jangan terlalu konservatif — ini paper trading untuk belajar!

Jawab HANYA dengan JSON ini (tanpa backtick, tanpa teks lain):
{{
  "action": "BUY" or "SKIP",
  "entry_type": "market" or "limit",
  "entry_price_usd": float,
  "tp_price_usd": float,
  "sl_price_usd": float,
  "confidence": 0-100,
  "reasoning": "singkat max 2 kalimat",
  "skip_reason": "jika SKIP, alasan singkat"
}}
"""
        text = await self._call_api(session, prompt, max_tokens=300)
        if not text:
            return None
        try:
            text = text.replace("```json", "").replace("```", "").strip()
            # Try direct JSON parse
            try:
                return json.loads(text)
            except json.JSONDecodeError:
                pass
            # Try extract JSON from text
            import re
            json_match = re.search(r'\{[^{}]*"action"[^{}]*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
            # Try find any JSON object
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
            logging.error(f"AI analyze parse error: no JSON found | raw: {text[:200]}")
            return None
        except Exception as e:
            logging.error(f"AI analyze parse error: {e} | raw: {text[:200]}")
            return None

    async def improve_filters(
        self, session: aiohttp.ClientSession, state: BotState
    ) -> tuple:
        recent_losses_text = "\n".join([
            f"- {t.token_symbol}: Entry ${t.entry_price:.6f}, Exit ${t.exit_price:.6f}, "
            f"PnL {t.pnl_pct:+.1f}%, Score {t.entry_score}/100, Duration {t.duration_str}"
            for t in list(state.recent_losses)[-5:]
            if t.pnl_sol is not None
        ]) or "Tidak ada detail loss tersedia"

        current = state.filters
        prompt = f"""
Kamu adalah AI filter optimizer untuk trading bot Solana on-chain.

Bot mengalami {state.consecutive_losses} loss berturut-turut.
Current win rate: {state.win_rate*100:.1f}% (target: 55%).
Filter generation saat ini: #{current.generation}.

RECENT LOSSES:
{recent_losses_text}

FILTER SAAT INI:
{current.to_prompt()}

ANALISIS & TUGAS:
Cari pola di loss tersebut (entry score terlalu rendah? age terlalu baru?
buy/sell ratio lemah? market cap terlalu besar/kecil?), lalu sesuaikan filter
untuk meningkatkan win rate ke 55%+.

Strategi yang bisa dilakukan:
- Naikkan min_liquidity, min_volume_24h
- Perketat min_buy_sell_ratio
- Sesuaikan rentang price_change_5m
- Sesuaikan TP/SL (tp_multiplier / sl_multiplier)
- Naikkan min_age_minutes (hindari token terlalu baru)
- Naikkan min_holder_count

Jawab HANYA dengan JSON (tanpa backtick):
{{
  "min_liquidity_usd": float,
  "min_volume_24h_usd": float,
  "min_holder_count": int,
  "max_price_impact_pct": float,
  "min_price_change_5m": float,
  "max_price_change_5m": float,
  "min_tx_count_5m": int,
  "min_buy_sell_ratio": float,
  "min_market_cap_usd": float,
  "max_market_cap_usd": float,
  "bundle_threshold": float,
  "min_age_minutes": int,
  "max_age_hours": int,
  "tp_multiplier": float,
  "sl_multiplier": float,
  "improvement_notes": "apa yang diubah dan kenapa (max 3 kalimat)"
}}
"""
        text = await self._call_api(session, prompt, max_tokens=600)
        if not text:
            return self._fallback_improve(current)
        try:
            text = text.replace("```json", "").replace("```", "").strip()
            data = json.loads(text)
            notes = data.pop("improvement_notes", "Auto-improved")
            new_filters = FilterConfig(**data, generation=current.generation + 1)
            return new_filters, notes
        except Exception as e:
            logging.error(f"AI improve parse error: {e}")
            return self._fallback_improve(current)

    async def generate_pattern_update(
        self, session: aiohttp.ClientSession, state: BotState
    ) -> Optional[str]:
        """Setiap 10 trade, AI update pattern library"""
        finished = state.finished_trades[-10:]
        if len(finished) < 5:
            return None

        wins = [t for t in finished if t.pnl_sol and t.pnl_sol > 0]
        losses = [t for t in finished if t.pnl_sol and t.pnl_sol <= 0]

        prompt = f"""
Analisis 10 trade terakhir bot Solana ini dan temukan pola BULLISH dan BEARISH.

WINS ({len(wins)}):
{chr(10).join([f"- {t.token_symbol}: Score {t.entry_score}/100, +{t.pnl_pct:.1f}%, Age {t.duration_str}" for t in wins]) or "Tidak ada"}

LOSSES ({len(losses)}):
{chr(10).join([f"- {t.token_symbol}: Score {t.entry_score}/100, {t.pnl_pct:.1f}%, Age {t.duration_str}" for t in losses]) or "Tidak ada"}

Tulis markdown ringkas berisi:
1. Win Rate batch ini
2. BULLISH PATTERNS ditemukan
3. BEARISH/AVOID PATTERNS ditemukan
4. Rekomendasi spesifik untuk batch berikutnya

Max 200 kata, format markdown.
"""
        return await self._call_api(session, prompt, max_tokens=400)

    def _fallback_improve(self, current: FilterConfig) -> tuple:
        f = copy.copy(current)
        f.min_liquidity_usd  = min(f.min_liquidity_usd * 1.3, 200_000)
        f.min_volume_24h_usd = min(f.min_volume_24h_usd * 1.3, 500_000)
        f.min_buy_sell_ratio = min(f.min_buy_sell_ratio + 0.2, 3.0)
        f.min_age_minutes    = min(f.min_age_minutes + 5, 30)
        f.generation        += 1
        return f, "Fallback: naikkan liquidity & volume 30%, perketat buy/sell ratio +0.2, naikkan min age +5m"


# ──────────────────────────────────────────────────────────────────
# TELEGRAM NOTIFIER
# ──────────────────────────────────────────────────────────────────

class TelegramBot:
    BASE = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"

    async def send(self, session: aiohttp.ClientSession, text: str, parse_mode: str = "HTML"):
        try:
            payload = {
                "chat_id": TELEGRAM_CHAT_ID,
                "text": text,
                "parse_mode": parse_mode,
                "disable_web_page_preview": True,
            }
            async with session.post(
                f"{self.BASE}/sendMessage",
                json=payload,
                timeout=aiohttp.ClientTimeout(total=10)
            ) as r:
                result = await r.json()
                if not result.get("ok"):
                    logging.warning(f"Telegram error: {result}")
        except Exception as e:
            logging.error(f"Telegram send error: {e}")

    def format_startup(self, paper: bool) -> str:
        mode = "📄 PAPER TRADING" if paper else "💰 LIVE TRADING"
        return f"""
🤖 <b>NDA4 AI TRADING BOT v2.0 STARTED</b>
{mode}

💼 Balance: {INITIAL_BALANCE_SOL} SOL
📦 Trade Size: {TRADE_SIZE_SOL} SOL per trade
🎯 Min Entry Score: {MIN_ENTRY_SCORE}/100
🎯 Target Win Rate: {TARGET_WIN_RATE*100:.0f}%
⚡ Max Open Trades: {MAX_OPEN_TRADES}
🔍 Scan Interval: {SCAN_INTERVAL_SEC}s
📊 Report Interval: 1 jam
🔧 Filter Gen: #1
🤖 AI Model: {OPENROUTER_MODEL}

Scanners: DexScreener + GMGN
Bot aktif scan token Solana secara real-time... 📡
""".strip()

    def format_trade_open(self, trade: Trade) -> str:
        icon   = "🟡" if trade.entry_type == "limit" else "🟢"
        status = "LIMIT ORDER" if trade.entry_type == "limit" else "MARKET ENTRY"
        paper  = "📄 PAPER" if trade.is_paper else "💰 LIVE"
        # GMGN indicators
        gmgn_info = ""
        if trade.gmgn_data:
            g = trade.gmgn_data
            gmgn_info = f"""
🔒 Contract: {'✅ Renounced' if g.get('renounced_mint') else '⚠️ Not Renounced'} | {'✅ Frozen' if g.get('renounced_freeze') else '❄️ Freezable'}
👥 Smart Money: {g.get('smart_degen_count', 0)} degen | {g.get('renowned_count', 0)} KOL
🔥 Hot Level: {'🔥' * g.get('hot_level', 0)}{'⬜' * (5 - g.get('hot_level', 0))}
⚠️ Risk: Rug {g.get('rug_ratio', 0):.2f} | Wash {'❌' if g.get('is_wash_trading') else '✅'} | Top10 {g.get('top_10_holder_rate', 0):.0%}
👨‍💻 Dev: {g.get('creator_token_status', 'unknown')}"""
        return f"""
{icon} <b>NEW TRADE — {status}</b> {paper}

🪙 Token: <b>${trade.token_symbol}</b>
📊 Entry Type: <b>{trade.entry_type.upper()}</b>
🏆 Score: <b>{trade.entry_score}/100</b>
💰 Entry Price: <b>${trade.entry_price:.8f}</b>
🎯 Take Profit: <b>${trade.tp_price:.8f}</b> (+{(trade.tp_price/trade.entry_price-1)*100:.1f}%)
🛑 Stop Loss: <b>${trade.sl_price:.8f}</b> (-{(1-trade.sl_price/trade.entry_price)*100:.1f}%)
💼 Size: <b>{trade.size_sol} SOL</b>{gmgn_info}

🔗 <a href="https://dexscreener.com/solana/{trade.token_address}">DexScreener</a> | <a href="https://gmgn.ai/sol/token/{trade.token_address}">GMGN</a>

📝 AI Reason: <i>{trade.ai_reasoning}</i>
🕐 {datetime.now().strftime('%H:%M:%S')}
""".strip()

    def format_trade_close(self, trade: Trade) -> str:
        won  = trade.pnl_sol and trade.pnl_sol > 0
        icon = "✅" if won else "❌"
        paper = "📄 PAPER" if trade.is_paper else "💰 LIVE"
        return f"""
{icon} <b>TRADE CLOSED — {'PROFIT' if won else 'LOSS'}</b> {paper}

🪙 Token: <b>${trade.token_symbol}</b>
📊 Exit Reason: <b>{trade.status.replace('_', ' ').upper()}</b>
🏆 Entry Score: <b>{trade.entry_score}/100</b>
💰 Entry: <b>${trade.entry_price:.8f}</b>
💱 Exit: <b>${trade.exit_price:.8f}</b>
{'📈' if won else '📉'} PnL: <b>{trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)</b>
⏱ Duration: {trade.duration_str}
🕐 {datetime.now().strftime('%H:%M:%S')}
""".strip()

    def format_filter_improve(self, old_gen: int, new_gen: int, notes: str) -> str:
        return f"""
🔧 <b>AI FILTER IMPROVED</b>

Generation: {old_gen} → {new_gen}
Trigger: 3x loss berturut-turut

📋 Perubahan:
<i>{notes}</i>

Bot akan lebih selektif dalam memilih entry. 💪
""".strip()

    def format_risk_alert(self, reason: str) -> str:
        return f"""
⚠️ <b>RISK MANAGEMENT ALERT</b>

🚨 {reason}

Bot berhenti trading sementara untuk proteksi kapital.
Review manual diperlukan.
""".strip()

    def format_hourly_report(self, state: BotState) -> str:
        open_trades   = state.open_trades
        pending       = [t for t in open_trades if t.status == "pending_limit"]
        running       = [t for t in open_trades if t.status == "open"]
        uptime        = timedelta(seconds=int(time.time() - state.started_at))
        mode_label    = "📄 PAPER" if PAPER_TRADE else "💰 LIVE"
        pnl_emoji     = "📈" if state.total_pnl_sol >= 0 else "📉"

        lines = [
            f"📊 <b>LAPORAN JAM — {datetime.now().strftime('%H:%M')} | {mode_label}</b>",
            f"━━━━━━━━━━━━━━━━━━━━",
            f"⏱ Uptime: {str(uptime).split('.')[0]}",
            f"💼 Balance: <b>{state.balance_sol:.4f} SOL</b>",
            f"{pnl_emoji} Total PnL: <b>{state.total_pnl_sol:+.4f} SOL</b>",
            f"📊 Portfolio: <b>{state.portfolio_change_pct*100:+.1f}%</b>",
            f"",
            f"📉 <b>STATISTIK TRADE</b>",
            f"Total Trade: {state.total_trades}",
            f"✅ Win: {state.winning_trades} | ❌ Loss: {state.losing_trades}",
            f"🎯 Win Rate: <b>{state.win_rate*100:.1f}%</b> (Target: {TARGET_WIN_RATE*100:.0f}%)",
            f"🔁 Filter Gen: #{state.filters.generation} | Improve: {state.improve_count}x",
            f"",
        ]

        if running:
            lines.append(f"🟢 <b>POSISI TERBUKA ({len(running)})</b>")
            for t in running:
                if t.current_price and t.entry_price:
                    pct     = (t.current_price - t.entry_price) / t.entry_price * 100
                    pnl_sol = (t.current_price - t.entry_price) / t.entry_price * t.size_sol
                    lines.append(
                        f"• ${t.token_symbol} [{t.entry_score}/100] | "
                        f"Entry ${t.entry_price:.6f} | Now ${t.current_price:.6f} | "
                        f"{'📈' if pct >= 0 else '📉'} {pct:+.1f}% ({pnl_sol:+.4f} SOL)"
                    )
                    lines.append(f"  🎯 TP: ${t.tp_price:.6f} | 🛑 SL: ${t.sl_price:.6f}")
            lines.append("")

        if pending:
            lines.append(f"🟡 <b>LIMIT ORDER ({len(pending)})</b>")
            for t in pending:
                lines.append(
                    f"• ${t.token_symbol} | Limit: ${t.entry_price:.6f} | "
                    f"TP: ${t.tp_price:.6f} | SL: ${t.sl_price:.6f}"
                )
            lines.append("")

        recent_closed = [t for t in state.finished_trades[-5:] if t.status in ("tp_hit", "sl_hit")]
        if recent_closed:
            lines.append(f"📋 <b>TRADE TERAKHIR</b>")
            for t in recent_closed:
                icon = "✅" if t.status == "tp_hit" else "❌"
                lines.append(f"{icon} ${t.token_symbol} [{t.entry_score}/100] | {t.pnl_sol:+.4f} SOL ({t.pnl_pct:+.1f}%)")
            lines.append("")

        lines.append(f"🔍 Scan: {state.scanned_tokens_today} | Skip: {state.skipped_tokens_today}")
        lines.append(f"⚙️ Gen #{state.filters.generation} | Min Score: {MIN_ENTRY_SCORE}")
        lines.append(f"🤖 Model: {OPENROUTER_MODEL}")

        return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────
# JOURNAL MANAGER
# ──────────────────────────────────────────────────────────────────

class JournalManager:
    def __init__(self):
        self._trade_batch = []

    def log_trade_open(self, trade: Trade, token: TokenData):
        entry = f"""
## Trade #{trade.id} — {datetime.now().strftime('%Y-%m-%d %H:%M')}

**Token**: {token.name} ({trade.token_symbol}) — `{trade.token_address}`
**Scanner**: DexScreener
**Entry Price**: ${trade.entry_price:.8f}
**Position Size**: {trade.size_sol} SOL ({"Paper" if trade.is_paper else "Live"})
**Entry Score**: {trade.entry_score}/100
**Entry Type**: {trade.entry_type.upper()}
**TP**: ${trade.tp_price:.8f} | **SL**: ${trade.sl_price:.8f}

### Entry Reasoning
- {trade.ai_reasoning}
- Liquidity: ${token.liquidity_usd:,.0f} | Volume 24h: ${token.volume_24h:,.0f}
- Buy/Sell 5m: {token.buy_count_5m}/{token.sell_count_5m} | Price change 5m: {token.price_change_5m:+.1f}%
- Age: {token.age_minutes:.0f} menit | Holders: {token.holder_count}
"""
        append_to_journal(entry)

    def log_trade_close(self, trade: Trade):
        won  = trade.pnl_sol and trade.pnl_sol > 0
        icon = "✅ WIN" if won else "❌ LOSS"
        outcome = f"""
### Outcome — {icon}
- **Exit Price**: ${trade.exit_price:.8f}
- **Exit Reason**: {trade.status.replace('_', ' ').upper()}
- **PnL**: {trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)
- **Duration**: {trade.duration_str}

### Learnings
- _[Bot akan update otomatis saat 10 trade selesai]_

---
"""
        append_to_journal(outcome)
        self._trade_batch.append(trade)

    def should_update_strategy(self) -> bool:
        return len(self._trade_batch) >= 10

    def flush_batch(self) -> list:
        batch = self._trade_batch[:]
        self._trade_batch.clear()
        return batch

    def log_strategy_iteration(self, state: BotState, notes: str):
        finished = state.finished_trades
        wins     = sum(1 for t in finished if t.pnl_sol and t.pnl_sol > 0)
        losses   = sum(1 for t in finished if t.pnl_sol and t.pnl_sol <= 0)
        wr       = wins / (wins + losses) * 100 if (wins + losses) > 0 else 0
        avg_win  = sum(t.pnl_pct for t in finished if t.pnl_pct and t.pnl_pct > 0) / max(wins, 1)
        avg_loss = sum(t.pnl_pct for t in finished if t.pnl_pct and t.pnl_pct <= 0) / max(losses, 1)

        entry = f"""
## Strategy Iteration #{state.improve_count} — {datetime.now().strftime('%Y-%m-%d %H:%M')}
Filter Generation: #{state.filters.generation}

### Performance
- Win Rate: {wr:.1f}%
- Avg Win: +{avg_win:.1f}% | Avg Loss: {avg_loss:.1f}%
- Net PnL: {state.total_pnl_sol:+.4f} SOL

### AI Pattern Notes
{notes}

---
"""
        append_to_strategy(entry)


# ──────────────────────────────────────────────────────────────────
# TRADING ENGINE — Main orchestrator
# ──────────────────────────────────────────────────────────────────

class TradingEngine:
    def __init__(self):
        self.scanner = SolanaScanner()
        self.ai      = AIAgent()
        self.filter  = FilterEngine()
        self.tg      = TelegramBot()
        self.journal = JournalManager()
        self.state   = BotState()

    async def run(self):
        init_reference_files()
        logging.info("🚀 NDA4 Bot v2 started!")
        async with aiohttp.ClientSession() as session:
            await self.tg.send(session, self.tg.format_startup(PAPER_TRADE))
            await asyncio.gather(
                self._scan_loop(session),
                self._price_update_loop(session),
                self._report_loop(session),
            )

    # ── Scan loop ──────────────────────────────────────────────────

    async def _scan_loop(self, session: aiohttp.ClientSession):
        while True:
            try:
                await self._do_scan(session)
            except Exception as e:
                logging.error(f"Scan loop error: {e}")
            await asyncio.sleep(SCAN_INTERVAL_SEC)

    async def _do_scan(self, session: aiohttp.ClientSession):
        if not self.state.can_open_trade():
            reason = (
                "paused (too many consecutive losses)" if self.state.paused_due_to_losses
                else "daily loss limit hit" if self.state.daily_loss_triggered
                else f"max trades open ({len(self.state.open_trades)}/{MAX_OPEN_TRADES})"
                if len(self.state.open_trades) >= MAX_OPEN_TRADES
                else f"insufficient balance ({self.state.balance_sol:.3f} SOL)"
            )
            logging.info(f"Skip scan: {reason}")
            return

        trending   = await self.scanner.get_trending_tokens(session)
        new_tokens = await self.scanner.get_new_tokens(session)
        all_tokens = list({t.address: t for t in (trending + new_tokens) if t.address}.values())
        self.state.scanned_tokens_today += len(all_tokens)

        open_addresses = {t.token_address for t in self.state.open_trades}
        candidates = []

        for token in all_tokens:
            if token.address in open_addresses:
                continue
            score = token.entry_score()
            if score < MIN_ENTRY_SCORE:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: score {score} < {MIN_ENTRY_SCORE}")
                continue
            passed, reason = self.filter.passes(token, self.state.filters)
            if not passed:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: {reason}")
                continue
            candidates.append(token)

        if not candidates:
            logging.info("No candidates passed filters this scan")
            return

        # Sort by entry score (desc), then by price_change_5m
        candidates.sort(key=lambda t: (t.entry_score(), t.price_change_5m), reverse=True)
        logging.info(f"Candidates: {len(candidates)} | Top: {candidates[0].symbol} (score={candidates[0].entry_score()})")

        for token in candidates[:2]:
            if not self.state.can_open_trade():
                break
            decision = await self.ai.analyze_token(session, token, self.state)
            if not decision:
                await asyncio.sleep(2)
                continue
            action = decision.get("action", "SKIP")
            confidence = decision.get("confidence", 0)
            logging.info(f"AI decision: {token.symbol} -> {action} (confidence={confidence})")
            if action == "BUY" and confidence >= 20:
                await self._open_trade(session, token, decision)
            await asyncio.sleep(15)  # avoid OpenRouter rate limit

    async def _open_trade(self, session: aiohttp.ClientSession, token: TokenData, decision: dict):
        entry_type  = decision.get("entry_type", "market")
        entry_price = float(decision.get("entry_price_usd", token.price_usd))
        tp_price    = float(decision.get("tp_price_usd", entry_price * self.state.filters.tp_multiplier))
        sl_price    = float(decision.get("sl_price_usd", entry_price * self.state.filters.sl_multiplier))
        reasoning   = decision.get("reasoning", "")

        # Validasi TP/SL
        tp_price = max(tp_price, entry_price * 1.10)          # min TP +10%
        sl_price = min(sl_price, entry_price * (1 - STOP_LOSS_PCT))  # max SL -30%
        sol_usd  = token.price_usd / token.price_sol if token.price_sol > 0 else 150

        trade = Trade(
            id=self.state.new_trade_id(),
            token_address=token.address,
            token_symbol=token.symbol,
            entry_type=entry_type,
            entry_price=entry_price,
            entry_price_sol=entry_price / sol_usd,
            tp_price=tp_price,
            sl_price=sl_price,
            size_sol=TRADE_SIZE_SOL,
            status="pending_limit" if entry_type == "limit" else "open",
            opened_at=time.time(),
            current_price=token.price_usd,
            ai_reasoning=reasoning,
            entry_score=token.entry_score(),
            is_paper=PAPER_TRADE,
        )

        self.state.trades.append(trade)
        self.state.balance_sol -= TRADE_SIZE_SOL
        self.state.total_trades += 1

        logging.info(
            f"OPEN {trade.id} ${token.symbol} {entry_type} @ ${entry_price:.8f} "
            f"| Score: {trade.entry_score}/100"
        )
        self.journal.log_trade_open(trade, token)
        await self.tg.send(session, self.tg.format_trade_open(trade))

    # ── Price update & TP/SL check ─────────────────────────────────

    async def _price_update_loop(self, session: aiohttp.ClientSession):
        while True:
            try:
                await self._update_prices(session)
            except Exception as e:
                logging.error(f"Price update error: {e}")
            await asyncio.sleep(15)

    async def _update_prices(self, session: aiohttp.ClientSession):
        for trade in list(self.state.open_trades):
            token_data = await self.scanner.get_token_detail(session, trade.token_address)
            if not token_data:
                continue

            current_price    = token_data.price_usd
            trade.current_price = current_price
            trade.last_updated  = time.time()

            # Aktifkan limit order
            if trade.status == "pending_limit":
                if current_price <= trade.entry_price:
                    trade.status = "open"
                    logging.info(f"Limit filled: {trade.id} @ ${current_price:.8f}")
                    await self.tg.send(session,
                        f"🟢 <b>LIMIT ORDER FILLED</b>\n"
                        f"${trade.token_symbol} @ ${trade.entry_price:.8f}\n"
                        f"TP: ${trade.tp_price:.8f} | SL: ${trade.sl_price:.8f}"
                    )
                continue

            # Check TP/SL
            if current_price >= trade.tp_price:
                await self._close_trade(session, trade, current_price, "tp_hit")
            elif current_price <= trade.sl_price:
                await self._close_trade(session, trade, current_price, "sl_hit")

    async def _close_trade(
        self, session: aiohttp.ClientSession, trade: Trade, exit_price: float, reason: str
    ):
        trade.exit_price = exit_price
        trade.closed_at  = time.time()
        trade.status     = reason

        pct = (exit_price - trade.entry_price) / trade.entry_price
        trade.pnl_pct = pct * 100
        trade.pnl_sol = pct * trade.size_sol

        self.state.total_pnl_sol += trade.pnl_sol
        self.state.balance_sol   += TRADE_SIZE_SOL + trade.pnl_sol

        won = reason == "tp_hit"
        if won:
            self.state.winning_trades    += 1
            self.state.consecutive_losses = 0
            self.state.paused_due_to_losses = False
        else:
            self.state.losing_trades      += 1
            self.state.consecutive_losses += 1
            self.state.recent_losses.append(trade)

        logging.info(
            f"CLOSE {trade.id} ${trade.token_symbol} {reason} "
            f"@ ${exit_price:.8f} | PnL: {trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)"
        )

        self.journal.log_trade_close(trade)
        await self.tg.send(session, self.tg.format_trade_close(trade))

        # Risk management checks
        await self._check_risk_rules(session)

        # Auto-improve filters setelah 3x loss
        if self.state.consecutive_losses >= CONSECUTIVE_LOSS_TRIGGER:
            await self._improve_filters(session)

        # Update strategy setiap 10 trade
        if self.journal.should_update_strategy():
            await self._update_strategy(session)

    # ── Risk management ─────────────────────────────────────────────

    async def _check_risk_rules(self, session: aiohttp.ClientSession):
        # Rule 1: Daily loss limit
        if self.state.check_daily_loss_limit():
            msg = f"Daily loss limit {MAX_DAILY_LOSS_PCT*100:.0f}% terpicu. Portfolio: {self.state.portfolio_change_pct*100:.1f}%"
            logging.warning(f"⚠️ {msg}")
            await self.tg.send(session, self.tg.format_risk_alert(msg))

        # Rule 2: Consecutive losses pause
        if self.state.consecutive_losses >= MAX_CONSECUTIVE_LOSSES:
            self.state.paused_due_to_losses = True
            msg = f"{MAX_CONSECUTIVE_LOSSES}x consecutive losses. Bot di-pause untuk review."
            logging.warning(f"⚠️ {msg}")
            await self.tg.send(session, self.tg.format_risk_alert(msg))

    # ── Filter improvement ──────────────────────────────────────────

    async def _improve_filters(self, session: aiohttp.ClientSession):
        old_gen = self.state.filters.generation
        logging.info(f"🔧 Improving filters (gen {old_gen})...")
        new_filters, notes = await self.ai.improve_filters(session, self.state)
        self.state.filters             = new_filters
        self.state.consecutive_losses  = 0
        self.state.improve_count      += 1

        logging.info(f"✅ Filter improved: gen {old_gen} → {new_filters.generation}")
        await self.tg.send(session, self.tg.format_filter_improve(old_gen, new_filters.generation, notes))

    # ── Strategy pattern update ─────────────────────────────────────

    async def _update_strategy(self, session: aiohttp.ClientSession):
        batch = self.journal.flush_batch()
        logging.info(f"📚 Updating strategy with {len(batch)} trade batch...")
        pattern_notes = await self.ai.generate_pattern_update(session, self.state)
        if pattern_notes:
            self.journal.log_strategy_iteration(self.state, pattern_notes)
            await self.tg.send(session,
                f"📚 <b>STRATEGY UPDATE</b>\n\n"
                f"Batch {self.state.total_trades} trade dianalisis.\n\n"
                f"<i>{pattern_notes[:400]}...</i>"
            )

    # ── Hourly report ───────────────────────────────────────────────

    async def _report_loop(self, session: aiohttp.ClientSession):
        await asyncio.sleep(REPORT_INTERVAL_SEC)
        while True:
            try:
                report = self.tg.format_hourly_report(self.state)
                await self.tg.send(session, report)
                self.state.last_report_at = time.time()
                logging.info("📊 Hourly report sent")
            except Exception as e:
                logging.error(f"Report error: {e}")
            await asyncio.sleep(REPORT_INTERVAL_SEC)


# ──────────────────────────────────────────────────────────────────
# ENTRY POINT
# ──────────────────────────────────────────────────────────────────

async def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        handlers=[
            logging.StreamHandler(),
            logging.FileHandler("bot.log", encoding="utf-8"),
        ],
    )

    missing = []
    if TELEGRAM_BOT_TOKEN  == "YOUR_BOT_TOKEN":      missing.append("TELEGRAM_BOT_TOKEN")
    if TELEGRAM_CHAT_ID    == "YOUR_CHAT_ID":        missing.append("TELEGRAM_CHAT_ID")
    if OPENROUTER_API_KEY  == "YOUR_OPENROUTER_KEY": missing.append("OPENROUTER_API_KEY")

    if missing:
        print(f"\n❌ Set environment variables dulu: {', '.join(missing)}")
        print("   Contoh: export TELEGRAM_BOT_TOKEN=xxx")
        print("   Atau buat file .env dan load dengan python-dotenv\n")
        return

    mode = "📄 PAPER TRADING (simulasi)" if PAPER_TRADE else "💰 LIVE TRADING (real money!)"
    print(f"\n{'='*60}")
    print(f"  NDA4 AI TRADING BOT v2.0")
    print(f"  Mode: {mode}")
    print(f"  Balance: {INITIAL_BALANCE_SOL} SOL | Trade size: {TRADE_SIZE_SOL} SOL")
    print(f"  Min Entry Score: {MIN_ENTRY_SCORE}/100 | AI: {OPENROUTER_MODEL}")
    print(f"{'='*60}\n")

    engine = TradingEngine()
    await engine.run()


if __name__ == "__main__":
    asyncio.run(main())
