"""
╔══════════════════════════════════════════════════════════════════╗
║  NDA4 AI AGENT SOLANA TRADING BOT v2.1 (PATCHED)                 ║
║  + Telegram notif: limit hit, TP, SL                             ║
║  + Laporan 1 jam sync dengan trade running/pending/closed        ║
╚══════════════════════════════════════════════════════════════════╝

PATCH NOTES v2.1:
- notify_limit_hit()   → notif saat limit order ke-hit
- notify_tp_hit()      → notif saat TP tercapai
- notify_sl_hit()      → notif saat SL tercapai
- send_hourly_report() → laporan 1 jam: open + pending + closed + PnL + WR
- monitor_open_trades() → loop harga real-time & trigger notif TP/SL/Limit
"""

import asyncio
import aiohttp
import json
import logging
import os
import time
import copy
from datetime import datetime, timedelta
from typing import Optional
from dataclasses import dataclass, field
from collections import deque
from pathlib import Path

# ── CONFIG ────────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID   = os.getenv("TELEGRAM_CHAT_ID", "1404877677")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL   = os.getenv("OPENROUTER_MODEL", "openrouter/owl-alpha")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
GMGN_API_KEY       = os.getenv("GMGN_API_KEY")

PAPER_TRADE              = os.getenv("PAPER_TRADE", "true").lower() != "false"
INITIAL_BALANCE_SOL      = float(os.getenv("INITIAL_BALANCE", "1.0"))
TRADE_SIZE_SOL           = float(os.getenv("TRADE_SIZE", "0.03"))
MAX_OPEN_TRADES          = int(os.getenv("MAX_OPEN_TRADES", "10"))
SCAN_INTERVAL_SEC        = int(os.getenv("SCAN_INTERVAL", "60"))
REPORT_INTERVAL_SEC      = 3600
TARGET_WIN_RATE          = 0.55
CONSECUTIVE_LOSS_TRIGGER = 3
MIN_ENTRY_SCORE          = 55
MAX_DAILY_LOSS_PCT       = 0.20
MAX_CONSECUTIVE_LOSSES   = 5
STOP_LOSS_PCT            = 0.30
CHASE_LIMIT_MULTIPLIER   = 3.0

REFERENCES_DIR = Path("references")
JOURNAL_FILE   = REFERENCES_DIR / "trading_journal.md"
STRATEGY_FILE  = REFERENCES_DIR / "strategy_evolution.md"
WATCHLIST_FILE = REFERENCES_DIR / "wallet_watchlist.md"
BLACKLIST_FILE = REFERENCES_DIR / "token_blacklist.md"

# ── LOGGING ───────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)

# ── REFERENCE FILES ───────────────────────────────────────────────
def init_reference_files():
    REFERENCES_DIR.mkdir(exist_ok=True)
    if not JOURNAL_FILE.exists():
        JOURNAL_FILE.write_text("# Trading Journal\n\n_Auto-generated by NDA4 Bot v2.1_\n\n")
    if not STRATEGY_FILE.exists():
        STRATEGY_FILE.write_text(
            "# Strategy Evolution\n\n_Auto-generated by NDA4 Bot v2.1_\n\n"
            "## Initial Strategy — Generation 1\n"
            "- Min liquidity: $15k\n- Min volume 24h: $10k\n- Min holders: 100\n"
            "- Buy/sell ratio: 1.5x\n- TP: +25% | SL: -8%\n\n"
        )
    if not WATCHLIST_FILE.exists():
        WATCHLIST_FILE.write_text("# Smart Money Wallet Watchlist\n\n_Add wallets to track here_\n\n")
    if not BLACKLIST_FILE.exists():
        BLACKLIST_FILE.write_text("# Token Blacklist\n\n_Tokens/patterns to avoid_\n\n")

def append_to_journal(text: str):
    try:
        with open(JOURNAL_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Journal write error: {e}")

def append_to_strategy(text: str):
    try:
        with open(STRATEGY_FILE, "a", encoding="utf-8") as f:
            f.write(text + "\n")
    except Exception as e:
        logging.warning(f"Strategy write error: {e}")

# ── DATA STRUCTURES ───────────────────────────────────────────────
@dataclass
class FilterConfig:
    min_liquidity_usd: float    = 1_000
    min_volume_24h_usd: float   = 500
    min_holder_count: int       = 5
    max_price_impact_pct: float = 15.0
    min_price_change_5m: float  = -5.0
    max_price_change_5m: float  = 100.0
    min_tx_count_5m: int        = 0
    min_buy_sell_ratio: float   = 0.0
    min_market_cap_usd: float   = 1_000
    max_market_cap_usd: float   = 50_000_000
    require_renounced: bool     = False
    require_burned_lp: bool     = False
    bundle_threshold: float     = 0.25
    min_age_minutes: int        = 5
    max_age_hours: int          = 24
    tp_multiplier: float        = 1.25
    sl_multiplier: float        = 0.90
    generation: int             = 1

    def to_prompt(self) -> str:
        return f"""
CURRENT FILTER CONFIG (Generation {self.generation}):
- Minimum Liquidity: ${self.min_liquidity_usd:,.0f}
- Minimum 24h Volume: ${self.min_volume_24h_usd:,.0f}
- Minimum Holders: {self.min_holder_count}
- Max Price Impact: {self.max_price_impact_pct}%
- Price Change 5m Range: {self.min_price_change_5m}% - {self.max_price_change_5m}%
- Min Tx 5m: {self.min_tx_count_5m}
- Min Buy/Sell Ratio: {self.min_buy_sell_ratio}x
- Market Cap Range: ${self.min_market_cap_usd:,.0f} - ${self.max_market_cap_usd:,.0f}
- Max Bundle %: {self.bundle_threshold*100:.0f}%
- Token Age: {self.min_age_minutes}m - {self.max_age_hours}h
- TP: +{(self.tp_multiplier-1)*100:.0f}% | SL: -{(1-self.sl_multiplier)*100:.0f}%
"""


@dataclass
class TokenData:
    address: str
    symbol: str
    name: str
    price_usd: float
    price_sol: float
    liquidity_usd: float
    volume_24h: float
    volume_5m: float
    price_change_5m: float
    price_change_1h: float
    price_change_24h: float
    market_cap: float
    holder_count: int
    tx_count_5m: int
    buy_count_5m: int
    sell_count_5m: int
    age_minutes: float
    dex: str
    pair_address: str
    buy_sell_ratio: float      = 0.0
    rug_ratio: float           = 0.0
    smart_degen_count: int     = 0
    renowned_count: int        = 0
    renounced_mint: bool       = False
    renounced_freeze: bool     = False
    is_wash_trading: bool      = False
    hot_level: int             = 0
    creator_token_status: str  = ""
    is_honeypot: bool          = False
    top_10_holder_rate: float  = 0.0
    dev_token_burn_ratio: float= 0.0
    cto_flag: bool             = False
    scanned_at: float          = field(default_factory=time.time)

    def entry_score(self) -> int:
        score = 0
        if self.liquidity_usd >= 20_000: score += 15
        elif self.liquidity_usd >= 10_000: score += 12
        elif self.liquidity_usd >= 5_000:  score += 8
        elif self.liquidity_usd >= 1_000:  score += 4

        if self.holder_count >= 100: score += 10
        elif self.holder_count >= 50: score += 7
        elif self.holder_count >= 20: score += 5
        elif self.holder_count >= 5:  score += 2

        if   2 <= self.price_change_5m <= 30:  score += 20
        elif 1 <= self.price_change_5m <= 50:  score += 15
        elif 0.5 <= self.price_change_5m <= 1: score += 10
        elif -5 <= self.price_change_5m < 0.5: score += 5

        ratio = self.buy_count_5m / self.sell_count_5m if self.sell_count_5m > 0 else (self.buy_count_5m if self.buy_count_5m > 0 else 0)
        if ratio >= 2.0:   score += 10
        elif ratio >= 1.5: score += 7
        elif ratio >= 1.0: score += 5
        elif ratio > 0:    score += 2

        if self.volume_24h >= 50_000: score += 10
        elif self.volume_24h >= 10_000: score += 7
        elif self.volume_24h >= 1_000:  score += 4

        if   5 <= self.age_minutes <= 120:   score += 10
        elif 1 <= self.age_minutes <= 360:   score += 7
        elif self.age_minutes > 360:          score += 3

        if self.smart_degen_count >= 5:   score += 7
        elif self.smart_degen_count >= 2: score += 5
        elif self.smart_degen_count >= 1: score += 3
        if self.renowned_count >= 3: score += 3
        elif self.renowned_count >= 1: score += 2

        if self.renounced_mint and self.renounced_freeze: score += 4
        elif self.renounced_mint or self.renounced_freeze: score += 2
        if not self.is_wash_trading: score += 3
        if self.rug_ratio <= 0.1:   score += 3
        elif self.rug_ratio <= 0.3: score += 1

        if self.hot_level >= 3:   score += 5
        elif self.hot_level >= 2: score += 3
        elif self.hot_level >= 1: score += 1

        if self.creator_token_status == "creator_hold":  score -= 5
        elif self.creator_token_status == "creator_close": score += 2
        if self.top_10_holder_rate >= 0.5:   score -= 5
        elif self.top_10_holder_rate >= 0.3: score -= 2
        if self.is_honeypot: score -= 20

        return max(0, min(score, 100))


@dataclass
class Trade:
    id: str
    token_address: str
    token_symbol: str
    entry_type: str
    entry_price: float
    entry_price_sol: float
    tp_price: float
    sl_price: float
    size_sol: float
    status: str
    opened_at: float
    entry_score: int               = 0
    closed_at: Optional[float]    = None
    exit_price: Optional[float]   = None
    pnl_sol: Optional[float]      = None
    pnl_pct: Optional[float]      = None
    ai_reasoning: str              = ""
    current_price: float           = 0.0
    last_updated: float            = field(default_factory=time.time)
    is_paper: bool                 = True
    gmgn_data: Optional[dict]     = None
    # ── NEW: flag sudah notif ──────────────────────────────────
    notified_limit_hit: bool       = False
    notified_tp: bool              = False
    notified_sl: bool              = False

    @property
    def is_active(self):
        return self.status in ("open", "pending_limit")

    @property
    def pnl_display(self):
        if self.pnl_sol is None:
            if self.status == "open" and self.current_price:
                pnl = (self.current_price - self.entry_price) / self.entry_price * self.size_sol
                return f"{pnl:+.4f} SOL ({(self.current_price/self.entry_price-1)*100:+.1f}%)"
            return "—"
        return f"{self.pnl_sol:+.4f} SOL ({self.pnl_pct:+.1f}%)"

    @property
    def duration_str(self) -> str:
        end = self.closed_at or time.time()
        mins = int((end - self.opened_at) / 60)
        if mins < 60:
            return f"{mins}m"
        return f"{mins//60}h {mins%60}m"

    def unrealized_pnl(self) -> float:
        """PnL unrealized berdasarkan harga sekarang"""
        if not self.current_price or not self.entry_price:
            return 0.0
        return (self.current_price - self.entry_price) / self.entry_price * self.size_sol

    def unrealized_pct(self) -> float:
        if not self.current_price or not self.entry_price:
            return 0.0
        return (self.current_price / self.entry_price - 1) * 100


@dataclass
class BotState:
    balance_sol: float        = INITIAL_BALANCE_SOL
    initial_balance_sol: float= INITIAL_BALANCE_SOL
    trades: list              = field(default_factory=list)
    filters: FilterConfig     = field(default_factory=FilterConfig)
    consecutive_losses: int   = 0
    total_trades: int         = 0
    winning_trades: int       = 0
    losing_trades: int        = 0
    total_pnl_sol: float      = 0.0
    improve_count: int        = 0
    started_at: float         = field(default_factory=time.time)
    last_report_at: float     = field(default_factory=time.time)
    scanned_tokens_today: int = 0
    skipped_tokens_today: int = 0
    daily_loss_triggered: bool= False
    paused_due_to_losses: bool= False
    recent_losses: deque      = field(default_factory=lambda: deque(maxlen=10))
    trade_counter: int        = 0

    @property
    def win_rate(self) -> float:
        finished = self.winning_trades + self.losing_trades
        return self.winning_trades / finished if finished > 0 else 0.0

    @property
    def open_trades(self):
        return [t for t in self.trades if t.status == "open"]

    @property
    def pending_trades(self):
        return [t for t in self.trades if t.status == "pending_limit"]

    @property
    def active_trades(self):
        return [t for t in self.trades if t.is_active]

    @property
    def finished_trades(self):
        return [t for t in self.trades if not t.is_active]

    @property
    def portfolio_change_pct(self) -> float:
        if self.initial_balance_sol == 0:
            return 0.0
        return (self.balance_sol - self.initial_balance_sol) / self.initial_balance_sol

    def can_open_trade(self) -> bool:
        if self.daily_loss_triggered: return False
        if self.paused_due_to_losses: return False
        if len(self.active_trades) >= MAX_OPEN_TRADES: return False
        if self.balance_sol < TRADE_SIZE_SOL: return False
        return True

    def check_daily_loss_limit(self) -> bool:
        if self.portfolio_change_pct <= -MAX_DAILY_LOSS_PCT:
            self.daily_loss_triggered = True
            return True
        return False

    def new_trade_id(self) -> str:
        self.trade_counter += 1
        return f"T{self.trade_counter:04d}"

    def total_unrealized_pnl(self) -> float:
        return sum(t.unrealized_pnl() for t in self.open_trades)

    def total_exposure_sol(self) -> float:
        return sum(t.size_sol for t in self.active_trades)


# ════════════════════════════════════════════════════════════════
#  TELEGRAM NOTIFIER  (DIPERLUAS v2.1)
# ════════════════════════════════════════════════════════════════
class TelegramNotifier:
    BASE_URL = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"
    MODE_TAG = "📄 PAPER" if PAPER_TRADE else "💸 LIVE"

    async def send(self, session: aiohttp.ClientSession, text: str, parse_mode: str = "HTML") -> bool:
        if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
            logging.warning("Telegram token/chat_id not set, skipping notif.")
            return False
        try:
            async with session.post(
                f"{self.BASE_URL}/sendMessage",
                json={"chat_id": TELEGRAM_CHAT_ID, "text": text, "parse_mode": parse_mode},
                timeout=aiohttp.ClientTimeout(total=10),
            ) as r:
                ok = r.status == 200
                if not ok:
                    err = await r.text()
                    logging.warning(f"Telegram send failed {r.status}: {err[:100]}")
                return ok
        except Exception as e:
            logging.warning(f"Telegram error: {e}")
            return False

    # ── ENTRY notif (sudah ada, dipertahankan) ───────────────────
    async def notify_entry(self, session, trade: Trade):
        mode = "📋 LIMIT ORDER" if trade.entry_type == "limit" else "✅ MARKET BUY"
        emoji = "🟡" if trade.entry_type == "limit" else "🟢"
        msg = (
            f"{emoji} <b>{mode}</b> [{self.MODE_TAG}]\n"
            f"──────────────────\n"
            f"🪙 <b>{trade.token_symbol}</b>  |  #{trade.id}\n"
            f"📥 Entry   : <code>${trade.entry_price:.8f}</code>\n"
            f"🎯 TP      : <code>${trade.tp_price:.8f}</code>  "
            f"(+{(trade.tp_price/trade.entry_price-1)*100:.1f}%)\n"
            f"🛑 SL      : <code>${trade.sl_price:.8f}</code>  "
            f"(-{(1-trade.sl_price/trade.entry_price)*100:.1f}%)\n"
            f"💰 Size    : {trade.size_sol} SOL\n"
            f"⭐ Score   : {trade.entry_score}/100\n"
            f"💬 AI      : {trade.ai_reasoning}\n"
            f"🔗 <a href='https://dexscreener.com/solana/{trade.token_address}'>DexScreener</a>"
        )
        await self.send(session, msg)

    # ── LIMIT HIT notif (BARU) ───────────────────────────────────
    async def notify_limit_hit(self, session, trade: Trade):
        """Kirim notif saat limit order ke-hit (pending → open)"""
        msg = (
            f"✅ <b>LIMIT ORDER TERISI</b> [{self.MODE_TAG}]\n"
            f"──────────────────\n"
            f"🪙 <b>{trade.token_symbol}</b>  |  #{trade.id}\n"
            f"📥 Entry   : <code>${trade.entry_price:.8f}</code>\n"
            f"🎯 TP      : <code>${trade.tp_price:.8f}</code>  "
            f"(+{(trade.tp_price/trade.entry_price-1)*100:.1f}%)\n"
            f"🛑 SL      : <code>${trade.sl_price:.8f}</code>  "
            f"(-{(1-trade.sl_price/trade.entry_price)*100:.1f}%)\n"
            f"💰 Size    : {trade.size_sol} SOL\n"
            f"⏰ Waktu   : {datetime.now().strftime('%H:%M:%S')}\n"
            f"🔗 <a href='https://dexscreener.com/solana/{trade.token_address}'>DexScreener</a>"
        )
        await self.send(session, msg)

    # ── TP HIT notif (BARU) ──────────────────────────────────────
    async def notify_tp_hit(self, session, trade: Trade):
        """Kirim notif saat TP tercapai"""
        pnl_sol = trade.pnl_sol or 0
        pnl_pct = trade.pnl_pct or 0
        dur = trade.duration_str
        msg = (
            f"🎯 <b>TAKE PROFIT HIT!</b> [{self.MODE_TAG}]\n"
            f"──────────────────\n"
            f"🪙 <b>{trade.token_symbol}</b>  |  #{trade.id}\n"
            f"📥 Entry   : <code>${trade.entry_price:.8f}</code>\n"
            f"📤 Exit    : <code>${trade.exit_price:.8f}</code>\n"
            f"💰 PnL     : <b>+{pnl_sol:.4f} SOL</b>  (+{pnl_pct:.1f}%)\n"
            f"⏱ Durasi  : {dur}\n"
            f"⏰ Waktu   : {datetime.now().strftime('%H:%M:%S')}\n"
            f"🔗 <a href='https://dexscreener.com/solana/{trade.token_address}'>DexScreener</a>"
        )
        await self.send(session, msg)

    # ── SL HIT notif (BARU) ──────────────────────────────────────
    async def notify_sl_hit(self, session, trade: Trade):
        """Kirim notif saat SL tercapai"""
        pnl_sol = trade.pnl_sol or 0
        pnl_pct = trade.pnl_pct or 0
        dur = trade.duration_str
        msg = (
            f"🛑 <b>STOP LOSS HIT!</b> [{self.MODE_TAG}]\n"
            f"──────────────────\n"
            f"🪙 <b>{trade.token_symbol}</b>  |  #{trade.id}\n"
            f"📥 Entry   : <code>${trade.entry_price:.8f}</code>\n"
            f"📤 Exit    : <code>${trade.exit_price:.8f}</code>\n"
            f"💸 PnL     : <b>{pnl_sol:.4f} SOL</b>  ({pnl_pct:.1f}%)\n"
            f"⏱ Durasi  : {dur}\n"
            f"⏰ Waktu   : {datetime.now().strftime('%H:%M:%S')}\n"
            f"🔗 <a href='https://dexscreener.com/solana/{trade.token_address}'>DexScreener</a>"
        )
        await self.send(session, msg)

    # ── LAPORAN 1 JAM (DIPERBAIKI — sync dengan semua trade) ─────
    async def send_hourly_report(self, session, state: BotState):
        """
        Laporan tiap 1 jam yang sync dengan:
        - Trade RUNNING (open)
        - Trade PENDING (limit order belum ke-hit)
        - Trade CLOSED hari ini
        - Jumlah SOL, PnL, WR
        """
        now = datetime.now()
        uptime_mins = int((time.time() - state.started_at) / 60)
        uptime_str  = f"{uptime_mins//60}j {uptime_mins%60}m" if uptime_mins >= 60 else f"{uptime_mins}m"

        open_trades    = state.open_trades
        pending_trades = state.pending_trades
        closed_trades  = state.finished_trades

        # ── Kalkulasi PnL ──────────────────────────────────────
        realized_pnl    = state.total_pnl_sol
        unrealized_pnl  = state.total_unrealized_pnl()
        total_pnl_all   = realized_pnl + unrealized_pnl
        portfolio_pct   = state.portfolio_change_pct * 100
        exposure_sol    = state.total_exposure_sol()

        # Win rate
        total_finished  = state.winning_trades + state.losing_trades
        wr_str          = f"{state.win_rate*100:.1f}%" if total_finished > 0 else "N/A"
        wr_emoji        = "🟢" if state.win_rate >= TARGET_WIN_RATE else ("🟡" if state.win_rate >= 0.4 else "🔴")

        # ── Header ─────────────────────────────────────────────
        lines = [
            f"📊 <b>LAPORAN 1 JAM — {now.strftime('%d/%m %H:%M')}</b> [{self.MODE_TAG}]",
            f"━━━━━━━━━━━━━━━━━━━━━",
            f"⏱ Uptime   : {uptime_str}",
            f"💼 Balance  : <b>{state.balance_sol:.4f} SOL</b>",
            f"📦 Exposure : {exposure_sol:.4f} SOL",
            f"",
        ]

        # ── Trade RUNNING ──────────────────────────────────────
        lines.append(f"🟢 <b>RUNNING ({len(open_trades)})</b>")
        if open_trades:
            for t in open_trades:
                upnl = t.unrealized_pnl()
                upct = t.unrealized_pct()
                price_str = f"${t.current_price:.8f}" if t.current_price else "—"
                emoji = "📈" if upnl >= 0 else "📉"
                lines.append(
                    f"  {emoji} <b>{t.token_symbol}</b> #{t.id}"
                    f"\n     Entry ${t.entry_price:.8f} → Now {price_str}"
                    f"\n     uPnL <code>{upnl:+.4f} SOL ({upct:+.1f}%)</code>"
                    f"  [{t.duration_str}]"
                )
        else:
            lines.append("  — tidak ada trade running")
        lines.append("")

        # ── Trade PENDING (limit belum hit) ────────────────────
        lines.append(f"🟡 <b>PENDING LIMIT ({len(pending_trades)})</b>")
        if pending_trades:
            for t in pending_trades:
                cur = t.current_price or 0
                gap_pct = ((t.entry_price - cur) / cur * 100) if cur > 0 else 0
                lines.append(
                    f"  ⏳ <b>{t.token_symbol}</b> #{t.id}"
                    f"\n     Limit ${t.entry_price:.8f}  (gap {gap_pct:+.1f}% dari harga sekarang)"
                    f"\n     TP ${t.tp_price:.8f}  |  SL ${t.sl_price:.8f}"
                )
        else:
            lines.append("  — tidak ada pending order")
        lines.append("")

        # ── Trade CLOSED ──────────────────────────────────────
        # Tampilkan 5 terakhir yang closed
        recent_closed = closed_trades[-5:] if len(closed_trades) > 5 else closed_trades
        lines.append(f"📋 <b>CLOSED ({len(closed_trades)} total)</b>")
        if recent_closed:
            for t in recent_closed:
                emoji  = "✅" if (t.pnl_sol or 0) >= 0 else "❌"
                reason = t.status.upper()
                lines.append(
                    f"  {emoji} <b>{t.token_symbol}</b> #{t.id}"
                    f" [{reason}]  {t.pnl_sol:+.4f} SOL ({t.pnl_pct:+.1f}%)"
                )
        else:
            lines.append("  — belum ada trade closed")
        lines.append("")

        # ── Ringkasan PnL & WR ────────────────────────────────
        pnl_emoji  = "💚" if total_pnl_all >= 0 else "🔴"
        port_emoji = "📈" if portfolio_pct >= 0 else "📉"
        lines += [
            f"━━━━━━━━━━━━━━━━━━━━━",
            f"💰 <b>RINGKASAN PnL</b>",
            f"  Realized   : <code>{realized_pnl:+.4f} SOL</code>",
            f"  Unrealized : <code>{unrealized_pnl:+.4f} SOL</code>",
            f"  {pnl_emoji} Total     : <b>{total_pnl_all:+.4f} SOL</b>",
            f"  {port_emoji} Portfolio : <b>{portfolio_pct:+.2f}%</b>",
            f"",
            f"📈 <b>STATISTIK</b>",
            f"  {wr_emoji} Win Rate  : <b>{wr_str}</b>  ({state.winning_trades}W / {state.losing_trades}L)",
            f"  Total Trade : {state.total_trades}  |  Scanned: {state.scanned_tokens_today}",
            f"  Streak Loss : {state.consecutive_losses}x",
            f"  Filter Gen  : #{state.filters.generation}",
        ]

        if state.paused_due_to_losses:
            lines.append(f"\n⚠️ <b>BOT PAUSED</b> — {state.consecutive_losses} consecutive losses")
        if state.daily_loss_triggered:
            lines.append(f"\n🚨 <b>DAILY LOSS LIMIT HIT</b> — trading dihentikan hari ini")

        msg = "\n".join(lines)
        await self.send(session, msg)


# ════════════════════════════════════════════════════════════════
#  PRICE FETCHER — ambil harga real-time dari DexScreener
# ════════════════════════════════════════════════════════════════
class PriceFetcher:
    DEXSCREENER_TOKEN_URL = "https://api.dexscreener.com/latest/dex/tokens/{address}"

    async def get_price(self, session: aiohttp.ClientSession, token_address: str) -> Optional[float]:
        try:
            url = self.DEXSCREENER_TOKEN_URL.format(address=token_address)
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=8)) as r:
                if r.status != 200:
                    return None
                data = await r.json()
                pairs = data.get("pairs") or []
                if not pairs:
                    return None
                # Ambil pair dengan liquidity terbesar
                best = max(pairs, key=lambda x: float((x.get("liquidity") or {}).get("usd", 0) or 0))
                price = float(best.get("priceUsd", 0) or 0)
                return price if price > 0 else None
        except Exception:
            return None


# ════════════════════════════════════════════════════════════════
#  TRADE MONITOR — cek TP/SL/Limit secara real-time
# ════════════════════════════════════════════════════════════════
class TradeMonitor:
    """
    Loop yang berjalan setiap 30 detik:
    1. Update harga current untuk semua active trade
    2. Cek limit order → jika price <= entry_price → set open + kirim notif
    3. Cek TP → jika price >= tp_price → close trade + kirim notif
    4. Cek SL → jika price <= sl_price → close trade + kirim notif
    """

    def __init__(self, state: BotState, notifier: TelegramNotifier):
        self.state    = state
        self.notifier = notifier
        self.fetcher  = PriceFetcher()

    async def _close_trade(self, trade: Trade, exit_price: float, reason: str):
        """Close trade dan update state"""
        trade.status     = reason  # "tp_hit" / "sl_hit"
        trade.exit_price = exit_price
        trade.closed_at  = time.time()
        trade.pnl_pct    = (exit_price / trade.entry_price - 1) * 100
        trade.pnl_sol    = trade.size_sol * (exit_price / trade.entry_price - 1)
        self.state.total_pnl_sol += trade.pnl_sol
        self.state.balance_sol   += trade.size_sol + trade.pnl_sol  # kembalikan modal + PnL
        self.state.total_trades  += 1

        if trade.pnl_sol >= 0:
            self.state.winning_trades   += 1
            self.state.consecutive_losses = 0
        else:
            self.state.losing_trades     += 1
            self.state.consecutive_losses += 1
            self.state.recent_losses.append(trade)

        if self.state.consecutive_losses >= MAX_CONSECUTIVE_LOSSES:
            self.state.paused_due_to_losses = True

        self.state.check_daily_loss_limit()

        # Journal entry
        pnl_tag = "WIN" if trade.pnl_sol >= 0 else "LOSS"
        append_to_journal(
            f"\n### [{pnl_tag}] {trade.token_symbol} #{trade.id} — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            f"- Entry: ${trade.entry_price:.8f}  Exit: ${exit_price:.8f}\n"
            f"- PnL: {trade.pnl_sol:+.4f} SOL ({trade.pnl_pct:+.1f}%)  Reason: {reason}\n"
            f"- Duration: {trade.duration_str}  Score: {trade.entry_score}/100\n"
        )

    async def monitor_loop(self, session: aiohttp.ClientSession):
        """Main monitoring loop — jalankan sebagai asyncio task"""
        logging.info("TradeMonitor started — checking every 30s")
        while True:
            try:
                await self._tick(session)
            except Exception as e:
                logging.error(f"TradeMonitor error: {e}")
            await asyncio.sleep(30)

    async def _tick(self, session: aiohttp.ClientSession):
        active = self.state.active_trades
        if not active:
            return

        for trade in active:
            price = await self.fetcher.get_price(session, trade.token_address)
            if not price:
                continue

            # Update current price
            trade.current_price = price
            trade.last_updated  = time.time()

            # ── 1. Limit order ke-hit ──────────────────────────
            if trade.status == "pending_limit":
                if price <= trade.entry_price:
                    trade.status = "open"
                    if not trade.notified_limit_hit:
                        trade.notified_limit_hit = True
                        await self.notifier.notify_limit_hit(session, trade)
                        logging.info(f"[LIMIT HIT] {trade.token_symbol} #{trade.id} @ ${price:.8f}")
                    continue  # Skip TP/SL check di cycle ini

            # ── 2. TP check ────────────────────────────────────
            if trade.status == "open" and price >= trade.tp_price:
                if not trade.notified_tp:
                    trade.notified_tp = True
                    await self._close_trade(trade, price, "tp_hit")
                    await self.notifier.notify_tp_hit(session, trade)
                    logging.info(f"[TP HIT] {trade.token_symbol} #{trade.id} @ ${price:.8f}  PnL={trade.pnl_sol:+.4f}")
                continue

            # ── 3. SL check ────────────────────────────────────
            if trade.status == "open" and price <= trade.sl_price:
                if not trade.notified_sl:
                    trade.notified_sl = True
                    await self._close_trade(trade, price, "sl_hit")
                    await self.notifier.notify_sl_hit(session, trade)
                    logging.info(f"[SL HIT] {trade.token_symbol} #{trade.id} @ ${price:.8f}  PnL={trade.pnl_sol:+.4f}")
                continue


# ════════════════════════════════════════════════════════════════
#  HOURLY REPORT SCHEDULER
# ════════════════════════════════════════════════════════════════
async def hourly_report_loop(session: aiohttp.ClientSession, state: BotState, notifier: TelegramNotifier):
    """Task yang kirim laporan tiap 1 jam"""
    logging.info("Hourly report scheduler started")
    while True:
        await asyncio.sleep(REPORT_INTERVAL_SEC)
        try:
            await notifier.send_hourly_report(session, state)
            state.last_report_at = time.time()
            logging.info("Hourly report sent")
        except Exception as e:
            logging.error(f"Hourly report error: {e}")


# ════════════════════════════════════════════════════════════════
#  SCANNER (GMGN + DexScreener fallback)
# ════════════════════════════════════════════════════════════════
class SolanaScanner:
    DEXSCREENER_BASE = "https://api.dexscreener.com/latest/dex"
    BOOST_URL = "https://api.dexscreener.com/token-boosts/latest/v1"

    async def _gmgn_cli(self, args: list) -> Optional[dict]:
        cmd = ["gmgn-cli"] + args
        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=20)
            if proc.returncode != 0:
                return None
            return json.loads(stdout.decode())
        except Exception:
            return None

    async def get_trending_tokens(self, session: aiohttp.ClientSession) -> list:
        tokens = []
        data = await self._gmgn_cli(["market", "trending", "--chain", "sol", "--interval", "5m"])
        if not data:
            return await self._fallback_trending(session)
        if data.get("code") != 0:
            return await self._fallback_trending(session)
        rank = (data.get("data") or {}).get("rank") or []
        for item in rank[:25]:
            token = self._parse_gmgn_token(item)
            if token:
                tokens.append(token)
        return tokens

    async def get_new_tokens(self, session: aiohttp.ClientSession) -> list:
        data = await self._gmgn_cli(["market", "trenches", "--chain", "sol", "--type", "new_creation"])
        if not data:
            return await self._fallback_new(session)
        tokens = []
        items = data.get("new_creation") or data.get("data", {}).get("list") or []
        if not items:
            for key in ("new_creation", "near_completion", "completed"):
                items = data.get(key) or []
                if items:
                    break
        for item in items[:20]:
            token = self._parse_gmgn_token(item)
            if token:
                tokens.append(token)
        return tokens

    def _parse_gmgn_token(self, item: dict) -> Optional[TokenData]:
        try:
            address   = item.get("address", "")
            symbol    = item.get("symbol", "???")
            name      = item.get("name", "Unknown")
            price_usd = float(item.get("price", 0) or 0)
            if price_usd <= 0:
                liq_val = float(item.get("initial_liquidity", 0) or item.get("liquidity", 0) or 0)
                price_usd = liq_val / 1e9 if liq_val > 0 else None
                if not price_usd:
                    return None

            pc = item.get("price_change_percent") or item.get("priceChange") or {}
            if isinstance(pc, (int, float)):
                ch5m, ch1h, ch24h = float(pc), 0.0, 0.0
            else:
                ch5m  = float(pc.get("m5", 0) or 0)
                ch1h  = float(pc.get("h1", 0) or 0)
                ch24h = float(pc.get("h24", 0) or 0)

            vol = item.get("volume") or {}
            if isinstance(vol, (int, float)):
                vol_24h, vol_5m = float(vol), 0.0
            else:
                vol_24h = float(vol.get("h24", 0) or 0)
                vol_5m  = float(vol.get("m5", 0)  or 0)

            swaps = item.get("swaps") or item.get("txns") or {}
            if isinstance(swaps, (int, float)):
                total_swaps = int(swaps)
                buys_5m = total_swaps // 2
                sells_5m = total_swaps - buys_5m
            else:
                buys_5m  = int(swaps.get("buys", 0) or 0)
                sells_5m = int(swaps.get("sells", 0) or 0)
            if buys_5m == 0 and sells_5m == 0:
                buys_5m  = int(item.get("buys_24h",  0) or 0)
                sells_5m = int(item.get("sells_24h", 0) or 0)

            created_at = item.get("open_timestamp", 0) or item.get("creation_timestamp", 0) or 0
            if created_at > 1e12:
                created_at /= 1000
            age_minutes = max(0, (time.time() - created_at) / 60) if created_at > 0 else 0
            ratio = buys_5m / sells_5m if sells_5m > 0 else (999.0 if buys_5m > 0 else 0.0)

            return TokenData(
                address=address, symbol=symbol, name=name,
                price_usd=price_usd, price_sol=float(item.get("price_native", 0) or 0),
                liquidity_usd=float(item.get("liquidity", 0) or 0),
                volume_24h=vol_24h, volume_5m=vol_5m,
                price_change_5m=ch5m, price_change_1h=ch1h, price_change_24h=ch24h,
                market_cap=float(item.get("market_cap", 0) or 0),
                holder_count=int(item.get("holder_count", 0) or 0),
                tx_count_5m=buys_5m + sells_5m, buy_count_5m=buys_5m, sell_count_5m=sells_5m,
                buy_sell_ratio=ratio, age_minutes=age_minutes,
                dex=item.get("dex", "") or "unknown",
                pair_address=item.get("pair_address", "") or "",
                rug_ratio=float(item.get("rug_ratio", 0) or 0),
                smart_degen_count=int(item.get("smart_degen_count", 0) or 0),
                renowned_count=int(item.get("renowned_count", 0) or 0),
                renounced_mint=bool(item.get("renounced_mint", 0)),
                renounced_freeze=bool(item.get("renounced_freeze_account", 0)),
                is_wash_trading=bool(item.get("is_wash_trading", False)),
                hot_level=int(item.get("hot_level", 0) or 0),
                creator_token_status=item.get("creator_token_status", "") or "",
                is_honeypot=bool(item.get("is_honeypot", False)),
                top_10_holder_rate=float(item.get("top_10_holder_rate", 0) or 0),
                dev_token_burn_ratio=float(item.get("dev_token_burn_ratio", 0) or 0),
                cto_flag=bool(item.get("cto_flag", 0)),
            )
        except Exception as e:
            logging.debug(f"GMGN parse error: {e}")
            return None

    async def _fallback_trending(self, session: aiohttp.ClientSession) -> list:
        tokens = []
        try:
            async with session.get(self.BOOST_URL, timeout=aiohttp.ClientTimeout(total=10)) as r:
                if r.status != 200:
                    return tokens
                boosts = await r.json()
                if not isinstance(boosts, list):
                    return tokens
                for boost in boosts[:15]:
                    addr = boost.get("tokenAddress", "")
                    if not addr:
                        continue
                    try:
                        async with session.get(
                            f"{self.DEXSCREENER_BASE}/tokens/{addr}",
                            timeout=aiohttp.ClientTimeout(total=8)
                        ) as r2:
                            if r2.status != 200:
                                continue
                            data = await r2.json()
                            pairs = data.get("pairs") or []
                            if not pairs:
                                continue
                            best = max(pairs, key=lambda x: float((x.get("liquidity") or {}).get("usd", 0) or 0))
                            token = self._parse_dex_pair(best)
                            if token:
                                tokens.append(token)
                    except Exception:
                        continue
                    await asyncio.sleep(0.3)
        except Exception as e:
            logging.warning(f"Fallback trending error: {e}")
        return tokens

    async def _fallback_new(self, session: aiohttp.ClientSession) -> list:
        tokens = []
        try:
            url = f"{self.DEXSCREENER_BASE}/search?q=pump+fun+solana"
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=12)) as r:
                if r.status != 200:
                    return tokens
                data = await r.json()
                pairs = [p for p in (data.get("pairs") or []) if p.get("chainId") == "solana"]
                for p in pairs[:20]:
                    token = self._parse_dex_pair(p)
                    if token:
                        tokens.append(token)
        except Exception as e:
            logging.warning(f"Fallback new tokens error: {e}")
        return tokens

    def _parse_dex_pair(self, p: dict) -> Optional[TokenData]:
        try:
            base = p.get("baseToken", {})
            price_usd = float(p.get("priceUsd", 0) or 0)
            if price_usd <= 0:
                return None
            liq   = p.get("liquidity", {})
            vol   = p.get("volume", {})
            pc    = p.get("priceChange", {})
            txns5 = p.get("txns", {}).get("m5", {})
            created_at = p.get("pairCreatedAt", 0)
            age_minutes = (time.time() * 1000 - (created_at or time.time() * 1000)) / 60000
            buy5  = int(txns5.get("buys", 0) or 0)
            sell5 = int(txns5.get("sells", 0) or 0)
            ratio = buy5 / sell5 if sell5 > 0 else (999.0 if buy5 > 0 else 0.0)
            return TokenData(
                address=base.get("address", ""), symbol=base.get("symbol", "???"),
                name=base.get("name", "Unknown"), price_usd=price_usd,
                price_sol=float(p.get("priceNative", 0) or 0),
                liquidity_usd=float(liq.get("usd", 0) or 0),
                volume_24h=float(vol.get("h24", 0) or 0), volume_5m=float(vol.get("m5", 0) or 0),
                price_change_5m=float(pc.get("m5", 0) or 0), price_change_1h=float(pc.get("h1", 0) or 0),
                price_change_24h=float(pc.get("h24", 0) or 0),
                market_cap=float(p.get("marketCap", 0) or 0), holder_count=0,
                tx_count_5m=buy5 + sell5, buy_count_5m=buy5, sell_count_5m=sell5,
                buy_sell_ratio=ratio, age_minutes=max(0, age_minutes),
                dex=p.get("dexId", "unknown"), pair_address=p.get("pairAddress", ""),
            )
        except Exception:
            return None


# ════════════════════════════════════════════════════════════════
#  FILTER ENGINE
# ════════════════════════════════════════════════════════════════
class FilterEngine:
    def passes(self, token: TokenData, cfg: FilterConfig) -> tuple:
        if token.liquidity_usd < cfg.min_liquidity_usd:
            return False, f"Liquidity ${token.liquidity_usd:,.0f} < ${cfg.min_liquidity_usd:,.0f}"
        if token.volume_24h < cfg.min_volume_24h_usd:
            return False, f"Volume24h ${token.volume_24h:,.0f} < ${cfg.min_volume_24h_usd:,.0f}"
        if token.price_change_5m < cfg.min_price_change_5m:
            return False, f"Momentum 5m {token.price_change_5m:+.1f}% terlalu lemah"
        if token.price_change_5m > cfg.max_price_change_5m:
            return False, f"Pump 5m {token.price_change_5m:+.1f}% terlalu tinggi"
        if token.tx_count_5m < cfg.min_tx_count_5m:
            return False, f"Tx 5m {token.tx_count_5m} < {cfg.min_tx_count_5m}"
        if 0 < token.market_cap < cfg.min_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu kecil"
        if token.market_cap > cfg.max_market_cap_usd:
            return False, f"MCap ${token.market_cap:,.0f} terlalu besar"
        if token.age_minutes < cfg.min_age_minutes:
            return False, f"Token terlalu baru ({token.age_minutes:.0f}m)"
        if token.age_minutes > cfg.max_age_hours * 60:
            return False, f"Token terlalu lama ({token.age_minutes/60:.1f}h)"
        if token.sell_count_5m > 0:
            ratio = token.buy_count_5m / token.sell_count_5m
            if ratio < cfg.min_buy_sell_ratio:
                return False, f"Buy/Sell ratio {ratio:.1f}x < {cfg.min_buy_sell_ratio}x"
        if token.holder_count > 0 and token.holder_count < cfg.min_holder_count:
            return False, f"Holders {token.holder_count} < {cfg.min_holder_count}"
        if token.is_wash_trading:
            return False, "Wash trading detected"
        if token.is_honeypot:
            return False, "Honeypot detected"
        if token.rug_ratio > 0.5:
            return False, f"Rug ratio {token.rug_ratio:.2f} too high"
        if token.top_10_holder_rate > 0.7:
            return False, f"Top 10 holders {token.top_10_holder_rate:.0%} too concentrated"
        return True, ""


# ════════════════════════════════════════════════════════════════
#  AI AGENT
# ════════════════════════════════════════════════════════════════
class AIAgent:
    def __init__(self):
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "HTTP-Referer": "https://github.com/notobraddo/solana-memescanner",
            "X-Title": "NDA4 Solana Trading Bot v2.1",
        }

    async def _call_api(self, session: aiohttp.ClientSession, prompt: str, max_tokens: int = 500, retries: int = 2) -> Optional[str]:
        payload = {
            "model": OPENROUTER_MODEL,
            "max_tokens": max_tokens,
            "messages": [{"role": "user", "content": prompt}],
        }
        for attempt in range(retries + 1):
            try:
                async with session.post(
                    OPENROUTER_BASE_URL, headers=self.headers, json=payload,
                    timeout=aiohttp.ClientTimeout(total=45)
                ) as r:
                    if r.status == 429:
                        await asyncio.sleep(10 * (attempt + 1))
                        continue
                    if r.status != 200:
                        return None
                    data = await r.json()
                    content = data["choices"][0]["message"]["content"]
                    return content.strip() if content else None
            except asyncio.TimeoutError:
                if attempt < retries:
                    await asyncio.sleep(10 * (attempt + 1))
            except Exception as e:
                logging.error(f"OpenRouter error: {e}")
                return None
        return None

    async def analyze_token(self, session: aiohttp.ClientSession, token: TokenData, state: BotState) -> Optional[dict]:
        score = token.entry_score()
        prompt = f"""
Kamu adalah AI trading agent Solana on-chain yang disiplin.
{state.filters.to_prompt()}

TOKEN: {token.symbol} ({token.address[:8]}...)
Price: ${token.price_usd:.8f} | Liq: ${token.liquidity_usd:,.0f} | MCap: ${token.market_cap:,.0f}
Vol24h: ${token.volume_24h:,.0f} | Age: {token.age_minutes:.0f}m | Score: {score}/100
Change 5m/1h/24h: {token.price_change_5m:+.1f}% / {token.price_change_1h:+.1f}% / {token.price_change_24h:+.1f}%
Tx5m: {token.tx_count_5m} (B:{token.buy_count_5m} S:{token.sell_count_5m})
GMGN: rug={token.rug_ratio:.2f} smart_degen={token.smart_degen_count} hot={token.hot_level} honeypot={'Y' if token.is_honeypot else 'N'}
Renounced: {'✅' if token.renounced_mint else '❌'} | Wash: {'⚠️' if token.is_wash_trading else '✅'}

BOT: Balance={state.balance_sol:.3f} SOL | Open={len(state.open_trades)}/{MAX_OPEN_TRADES} | WR={state.win_rate*100:.1f}%

INSTRUKSI: Putuskan BUY atau SKIP. Jika BUY tentukan entry_type(market/limit), prices, confidence.
Jawab HANYA JSON (tanpa backtick):
{{"action":"BUY"/"SKIP","entry_type":"market"/"limit","entry_price_usd":float,"tp_price_usd":float,"sl_price_usd":float,"confidence":0-100,"reasoning":"max 2 kalimat","skip_reason":"jika SKIP"}}
"""
        text = await self._call_api(session, prompt, max_tokens=300)
        if not text:
            return None
        try:
            import re
            text = text.replace("```json", "").replace("```", "").strip()
            try:
                return json.loads(text)
            except json.JSONDecodeError:
                pass
            match = re.search(r'\{.*\}', text, re.DOTALL)
            return json.loads(match.group()) if match else None
        except Exception as e:
            logging.error(f"AI parse error: {e} | {text[:100]}")
            return None

    async def improve_filters(self, session: aiohttp.ClientSession, state: BotState):
        recent_losses_text = "\n".join([
            f"- {t.token_symbol}: PnL {t.pnl_pct:+.1f}%, Score {t.entry_score}/100"
            for t in list(state.recent_losses)[-5:] if t.pnl_sol is not None
        ]) or "—"
        current = state.filters
        prompt = f"""
Optimizer filter bot Solana. {state.consecutive_losses} loss berturut. WR={state.win_rate*100:.1f}%
Recent losses:\n{recent_losses_text}
{current.to_prompt()}
Analisis pola, adjust filter untuk WR 55%+.
Jawab HANYA JSON (tanpa backtick):
{{"min_liquidity_usd":float,"min_volume_24h_usd":float,"min_holder_count":int,"max_price_impact_pct":float,"min_price_change_5m":float,"max_price_change_5m":float,"min_tx_count_5m":int,"min_buy_sell_ratio":float,"min_market_cap_usd":float,"max_market_cap_usd":float,"bundle_threshold":float,"min_age_minutes":int,"max_age_hours":int,"tp_multiplier":float,"sl_multiplier":float,"improvement_notes":"max 3 kalimat"}}
"""
        text = await self._call_api(session, prompt, max_tokens=600)
        if not text:
            return self._fallback_improve(current)
        try:
            text = text.replace("```json", "").replace("```", "").strip()
            data = json.loads(text)
            notes = data.pop("improvement_notes", "Auto-improved")
            return FilterConfig(**data, generation=current.generation + 1), notes
        except Exception as e:
            logging.error(f"AI improve parse error: {e}")
            return self._fallback_improve(current)

    def _fallback_improve(self, current: FilterConfig):
        new_f = copy.copy(current)
        new_f.min_liquidity_usd    = min(current.min_liquidity_usd * 1.5, 100_000)
        new_f.min_volume_24h_usd   = min(current.min_volume_24h_usd * 1.5, 500_000)
        new_f.min_buy_sell_ratio   = min(current.min_buy_sell_ratio + 0.2, 3.0)
        new_f.generation           = current.generation + 1
        return new_f, "Fallback: naikkan liquidity, volume, buy/sell ratio"


# ════════════════════════════════════════════════════════════════
#  MAIN BOT LOOP
# ════════════════════════════════════════════════════════════════
class NDA4Bot:
    def __init__(self):
        self.state    = BotState()
        self.scanner  = SolanaScanner()
        self.filters  = FilterEngine()
        self.ai       = AIAgent()
        self.notifier = TelegramNotifier()
        self.monitor  = TradeMonitor(self.state, self.notifier)
        self.seen_tokens: set = set()

    async def run(self):
        init_reference_files()
        logging.info("NDA4 Bot v2.1 starting...")

        connector = aiohttp.TCPConnector(limit=20)
        async with aiohttp.ClientSession(connector=connector) as session:
            # Kirim notif start
            await self.notifier.send(
                session,
                f"🚀 <b>NDA4 Bot v2.1 started</b>\n"
                f"Balance: {self.state.balance_sol:.4f} SOL | "
                f"Mode: {'PAPER' if PAPER_TRADE else 'LIVE'}\n"
                f"Max trades: {MAX_OPEN_TRADES} | Trade size: {TRADE_SIZE_SOL} SOL"
            )

            # Jalankan task paralel:
            # 1. Scan loop utama
            # 2. Monitor TP/SL/Limit
            # 3. Hourly report
            await asyncio.gather(
                self._scan_loop(session),
                self.monitor.monitor_loop(session),
                hourly_report_loop(session, self.state, self.notifier),
            )

    async def _scan_loop(self, session: aiohttp.ClientSession):
        logging.info("Scan loop started")
        while True:
            try:
                await self._scan_cycle(session)
            except Exception as e:
                logging.error(f"Scan cycle error: {e}")
            await asyncio.sleep(SCAN_INTERVAL_SEC)

    async def _scan_cycle(self, session: aiohttp.ClientSession):
        if not self.state.can_open_trade():
            logging.info(f"Cannot open trade: balance={self.state.balance_sol:.3f} open={len(self.state.active_trades)}")
            return

        # Scan tokens
        trending = await self.scanner.get_trending_tokens(session)
        new_tkns = await self.scanner.get_new_tokens(session)
        all_tokens = trending + new_tkns

        self.state.scanned_tokens_today += len(all_tokens)
        deduped = {t.address: t for t in all_tokens if t.address}.values()

        for token in deduped:
            if token.address in self.seen_tokens:
                continue
            if not self.state.can_open_trade():
                break

            # Hard filter
            ok, reason = self.filters.passes(token, self.state.filters)
            if not ok:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: {reason}")
                continue

            # Entry score check
            score = token.entry_score()
            if score < MIN_ENTRY_SCORE:
                self.state.skipped_tokens_today += 1
                logging.debug(f"SKIP {token.symbol}: score {score} < {MIN_ENTRY_SCORE}")
                continue

            # AI analysis
            ai_res = await self.ai.analyze_token(session, token, self.state)
            if not ai_res or ai_res.get("action") != "BUY":
                reason = ai_res.get("skip_reason", "AI: SKIP") if ai_res else "AI timeout"
                logging.info(f"AI SKIP {token.symbol}: {reason}")
                continue

            # Place trade
            await self._place_trade(session, token, ai_res)
            self.seen_tokens.add(token.address)

        # Auto-improve jika banyak losses
        if (self.state.consecutive_losses >= CONSECUTIVE_LOSS_TRIGGER
                and not self.state.paused_due_to_losses):
            await self._auto_improve(session)

    async def _place_trade(self, session: aiohttp.ClientSession, token: TokenData, ai_res: dict):
        entry_type  = ai_res.get("entry_type", "market")
        entry_price = float(ai_res.get("entry_price_usd", token.price_usd))
        tp_price    = float(ai_res.get("tp_price_usd", token.price_usd * self.state.filters.tp_multiplier))
        sl_price    = float(ai_res.get("sl_price_usd", token.price_usd * self.state.filters.sl_multiplier))
        confidence  = int(ai_res.get("confidence", 50))
        reasoning   = ai_res.get("reasoning", "")

        if entry_price <= 0 or tp_price <= entry_price or sl_price >= entry_price:
            logging.warning(f"Invalid prices for {token.symbol}, skipping")
            return

        trade = Trade(
            id                 = self.state.new_trade_id(),
            token_address      = token.address,
            token_symbol       = token.symbol,
            entry_type         = entry_type,
            entry_price        = entry_price,
            entry_price_sol    = token.price_sol,
            tp_price           = tp_price,
            sl_price           = sl_price,
            size_sol           = TRADE_SIZE_SOL,
            status             = "pending_limit" if entry_type == "limit" else "open",
            opened_at          = time.time(),
            entry_score        = token.entry_score(),
            ai_reasoning       = reasoning,
            current_price      = token.price_usd,
            is_paper           = PAPER_TRADE,
        )

        # Kurangi balance
        self.state.balance_sol -= TRADE_SIZE_SOL
        self.state.trades.append(trade)

        logging.info(
            f"[TRADE] {trade.status.upper()} {token.symbol} #{trade.id} "
            f"entry=${entry_price:.8f} TP=${tp_price:.8f} SL=${sl_price:.8f} "
            f"conf={confidence}"
        )

        # Notif entry
        await self.notifier.notify_entry(session, trade)

        # Journal
        append_to_journal(
            f"\n### [ENTRY] {token.symbol} #{trade.id} — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            f"- Type: {entry_type} | Entry: ${entry_price:.8f} | TP: ${tp_price:.8f} | SL: ${sl_price:.8f}\n"
            f"- Score: {trade.entry_score}/100 | Conf: {confidence}/100 | AI: {reasoning}\n"
        )

    async def _auto_improve(self, session: aiohttp.ClientSession):
        logging.info(f"Auto-improving filters (gen {self.state.filters.generation})...")
        result = await self.ai.improve_filters(session, self.state)
        if not result:
            return
        new_filters, notes = result
        self.state.filters = new_filters
        self.state.improve_count += 1
        self.state.consecutive_losses = 0

        msg = (
            f"🔧 <b>Filter Auto-Improved → Gen #{new_filters.generation}</b>\n"
            f"──────────────────\n"
            f"📝 {notes}\n"
            f"💧 Min Liq: ${new_filters.min_liquidity_usd:,.0f}\n"
            f"📊 Min Vol: ${new_filters.min_volume_24h_usd:,.0f}\n"
            f"🎯 TP: +{(new_filters.tp_multiplier-1)*100:.0f}%  "
            f"🛑 SL: -{(1-new_filters.sl_multiplier)*100:.0f}%"
        )
        await self.notifier.send(session, msg)
        append_to_strategy(
            f"\n## Generation {new_filters.generation} — {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
            f"{notes}\n{new_filters.to_prompt()}\n"
        )


# ════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    bot = NDA4Bot()
    try:
        asyncio.run(bot.run())
    except KeyboardInterrupt:
        logging.info("Bot stopped by user.")
